# pytest.ini
[pytest]
filterwarnings =
    error::pygsti.tools.exceptions.pyGSTiDeprecationWarning
    error::pygsti.tools.exceptions.DeprecatedPositionalArgumentsWarning
    error::pygsti.tools.exceptions.MissingDependencyWarning
    error::pygsti.tools.exceptions.PrepareThyself
    error::pygsti.tools.exceptions.NumericalDomainWarning
    error::pygsti.tools.exceptions.UnnamedReportWarning
    error::pygsti.tools.exceptions.StolenResourceWarning
    error::pygsti.tools.exceptions.OverparameterizationWarning
    error::pygsti.tools.exceptions.UntouchedModelNoiseKey
    error::pygsti.tools.exceptions.QiskitInteropWarning
    error::pygsti.tools.exceptions.CirqInteropWarning
    error::scipy.optimize.OptimizeWarning
    ignore:Created an evaluation tree that is inefficient:UserWarning
    ignore:invalid escape sequence:DeprecationWarning
    ignore:Using finite differencing to compute LindbladErrorGen derivative!:UserWarning

python_classes = 
    *Tester
    Test*
