#!/usr/bin/python
from __future__ import print_function
import subprocess, os, sys

print('Runnning post-merge hook - updating git hooks')

old_wd = os.getcwd()
os.chdir('hooks/')
subprocess.call(['sh', 'setup_hooks.sh'])
os.chdir(old_wd)

sys.exit(0)
