#!/usr/bin/python
from __future__       import print_function
from automation_tools import get_branchname, run_pylint
from hooksettings     import generates_pylint_report
import subprocess, os, sys

if __name__ == '__main__':

    branchname = get_branchname()

    if branchname in generates_pylint_report:
        run_pylint(['./lint.py', '--score'])

    # Reindent
    try:
        subprocess.call(['reindent', '-r', 'packages', 'test'])
        subprocess.call(['git', 'add', '-u'])
        subprocess.call(['git', 'commit', '--no-verify', '--amend', '--no-edit'])
        print('Reindentation finished')
    except Exception as e:
        print(e)
        print('Is reindent installed alongside python?\n' +
              'On ubuntu/debian, try: apt-get install python-examples')

    sys.exit(0)



