#!/usr/bin/python
from __future__   import print_function
from utilities    import get_branchname, run_pylint
from hooksettings import requires_pylint_pass
import subprocess, os, sys

if __name__ == '__main__':
    branchname = get_branchname()
    if branchname in requires_pylint_pass:
        passes = run_pylint(['./score.py']) # Compare current pylint score against that in pylint/config.yml
        sys.exit(int(passes))
    else:
        sys.exit(0)

