#!/usr/bin/env python
from __future__   import print_function
from hooksettings import no_ci_triggered # File extensions that don't trigger Travis CI
import subprocess, sys, os

output = subprocess.check_output(['git', 'diff', '--name-only'])
lines  = output.decode('utf-8').splitlines()

doCI   = False

print('%s files changed' % len(lines))
for line in lines:
    print('%s changed' % line)
    if line.count('.') > 0:
        # Do CI if any file extensions are anything other than those in no_ci_trigged 
        #   (which might be something like ['md', 'text'])
        #   ie If all of the changed files are either markdown or text, skip CI. Otherwise, do CI as normal
        extension = line.rsplit('.', 1)[1]
        print('Extension: %s' % extension)
        if extension not in no_ci_triggered:
            doCI = True
            break
    else:
        doCI = True
        break # Do CI for files with no extension

# Load default commit into memory
with open(sys.argv[1], 'r') as defaultcommit:
    defaultMsg = defaultcommit.read()

# Overwrite it:
with open(sys.argv[1], 'w') as commit:
    if not doCI:
        commit.write(
            '# The line below will skip Travis CI.\n' + 
            '# If this is not what you want, delete it.\n' + 
            '[ci skip]\n')
    commit.write(defaultMsg)

