#!/usr/bin/env python
from __future__ import print_function
import subprocess, sys, os

output = subprocess.check_output(['git', 'diff', '--name-only'])
print(os.getcwd())
print('-' + output.decode('utf-8') + '-')

with open(sys.argv[2]) as commit-msg:
    print(commit-msg.read())
