"""
Character gate set tomography (cGST) protocol objects
"""
#***************************************************************************************************
# Copyright 2015, 2019, 2025 National Technology & Engineering Solutions of Sandia, LLC (NTESS).
# Under the terms of Contract DE-NA0003525 with NTESS, the U.S. Government retains certain rights
# in this software.
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.  You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0 or in the LICENSE file in the root pyGSTi directory.
#***************************************************************************************************

import hashlib as _hashlib
import itertools as _itertools
import warnings as _warnings

import numpy as _np

from pygsti.algorithms import cgstdesign as _cgstdesign
from pygsti.algorithms import cgstfit as _cgstfit
from pygsti.algorithms import cgstgauge as _cgstgauge
from pygsti.algorithms import cgstinversion as _cgstinversion
from pygsti.baseobjs.label import Label as _Label
from pygsti.circuits import Circuit as _Circuit
from pygsti.protocols import protocol as _proto
from pygsti.protocols import vb as _vb
from pygsti.tools import chartools as _ct
from pygsti.tools.internalgates import standard_gatename_unitaries as _std_unitaries
from pygsti.tools.optools import unitary_to_pauligate as _unitary_to_pauligate

# Character gate set tomography (cGST) merges gate set tomography's amplifying
# germs with character randomized benchmarking's representation-theoretic
# filtering.  A cGST germ is a short circuit that (ideally) generates a small
# finite cyclic group.  Instead of only repeating the germ deterministically
# (GST), cGST inserts uniformly random powers of the germ and weights each
# circuit's outcome by the conjugated character, evaluated at the total germ
# power, of one irrep of that group.  Averaging kills every other irrep's
# contribution, so each character-weighted signal decays as a SINGLE
# exponential -- an effective T1 experiment (trivial irrep) or Ramsey
# experiment (complex irrep) for each germ -- rather than the multi-exponential
# mixtures ordinary GST must fit.
#
# Two sampling modes are supported:
#
# * 'reduced' : a fixed number `k0` of random germ powers act as "synthetic
#   SPAM" (an approximate projector onto the irrep) and the germ is then
#   repeated `k` more times deterministically.  The fitted per-`k` decay is the
#   noisy germ's own eigenvalue on the irrep's branch.
#
# * 'full' : at depth `k` the circuit is `k` i.i.d. random germ powers.  The
#   fitted per-`k` decay is then an eigenvalue of the group Fourier operator
#   (see pygsti.tools.chartools.projector_eigenvalue_map), which amplifies
#   phase deviations by (order-1)/2 and must be numerically inverted to obtain
#   the germ eigenvalue.
#
# * 'exact' : like 'reduced', but because a cyclic germ's circuit depends only
#   on the TOTAL germ power, the `k0` rounds of Monte-Carlo sampling can be
#   replaced by deterministic quadrature: one circuit per possible total
#   random power `n0`, importance-weighted by the exact convolution
#   probability `q(n0)`.  This evaluates the synthetic projector with zero
#   sampling error (at the cost of fixing the number of circuits per depth to
#   `k0*(order-1) + 1`), and only generalizes to larger, non-cyclic groups by
#   falling back to the Monte-Carlo modes.


class CharacterGSTGermDesign(_vb.BenchmarkingDesign):
    """
    A cGST decay experiment for a single germ, irrep, and fiducial pair.

    Circuits have the form `prep_fiducial + germ**n + meas_fiducial` where the
    total germ power `n` contains uniformly random contributions whose realized
    values are stored (per circuit) in `exponent_lists`, enabling
    character-weighted averaging in post-processing (see
    :meth:`character_weights`).

    Parameters
    ----------
    germ : Circuit
        The germ circuit.  Its ideal implementation must generate a cyclic
        group: `germ**group_order` must be the identity.

    group_order : int
        The order of the cyclic group generated by the ideal germ.

    irrep_index : int
        Which irrep of `Z_group_order` to target, in `[0, group_order)`.
        Index 0 is the trivial irrep (a T1-type decay experiment); any other
        index gives a complex character (a Ramsey-type decay experiment).

    depths : list of ints
        In 'reduced' mode, the number of deterministic germ repetitions; in
        'full' mode, the number of i.i.d. random germ powers.

    circuits_per_depth : int
        The number of (independently randomized) circuits at each depth.
        Best chosen as a multiple of `group_order`: random germ powers are
        stratified over the residue classes of the total power so that
        character weights of constant backgrounds cancel exactly when the
        residue counts are balanced.  Ignored in 'exact' mode, which fixes it
        to `num_projection_rounds * (group_order - 1) + 1`.

    prep_fiducial, meas_fiducial : Circuit, optional
        Fiducial circuits applied before/after the germ powers, mapping the
        native preparation/measurement onto the subspace the target irrep acts
        on.  Empty circuits by default.

    mode : {'reduced', 'full', 'exact'}, optional
        The sampling mode (see the module docstring).

    num_projection_rounds : int, optional
        The number of random germ powers (`k0`) in 'reduced' mode.  Unused in
        'full' mode.  Larger values purify the synthetic SPAM projection at the
        cost of longer circuits; the residual bias scales as
        `O(infidelity**(k0/2))`.

    qubit_labels : tuple, optional
        The qubits this experiment design applies to.  If None, the germ's
        line labels are used.

    seed : int, optional
        Seed for the random germ powers.

    descriptor : str, optional
        A description of the experiment design.
    """

    def __init__(self, germ, group_order, irrep_index, depths, circuits_per_depth,
                 prep_fiducial=None, meas_fiducial=None, mode='reduced',
                 num_projection_rounds=4, qubit_labels=None, seed=None,
                 descriptor='A cGST germ-decay experiment'):
        if mode not in ('reduced', 'full', 'exact'):
            raise ValueError("mode must be 'reduced', 'full' or 'exact', not '%s'" % mode)
        if not (0 <= irrep_index < group_order):
            raise ValueError("irrep_index must be in [0, group_order)")
        if mode == 'exact' and num_projection_rounds < 1:
            raise ValueError("'exact' mode requires num_projection_rounds >= 1")

        if qubit_labels is None:
            qubit_labels = germ.line_labels
        empty = _Circuit((), line_labels=germ.line_labels)
        prep_fiducial = prep_fiducial if (prep_fiducial is not None) else empty
        meas_fiducial = meas_fiducial if (meas_fiducial is not None) else empty

        if mode == 'full' and any(k < 1 for k in depths):
            raise ValueError("'full' mode requires depths >= 1 (depth = number of random germ powers)")

        rand_state = _np.random.RandomState(seed)
        success_outcome = '0' * len(qubit_labels)

        # Two variance-reduction refinements over naive i.i.d. sampling (both
        # leave the character-weighted average unchanged in expectation):
        #
        # 1. Residue stratification: the last random draw is adjusted so the
        #    circuits at each depth cycle deterministically through the residue
        #    classes of the total germ power (mod group_order).  With balanced
        #    residue counts (circuits_per_depth a multiple of group_order) the
        #    character average of any constant background is exactly zero.
        #
        # 2. Common random numbers ('reduced' mode only): the projection-round
        #    draws are made once per circuit index and REUSED at every depth.
        #    For a cyclic germ the channel depends only on the total power, so
        #    the draws' contribution to the signal becomes a depth-independent
        #    constant absorbed by the fit amplitude, instead of independent
        #    per-depth multiplicative noise on the decay estimate.
        if mode == 'exact':
            # one circuit per possible total random power; overrides circuits_per_depth
            circuits_per_depth = num_projection_rounds * (group_order - 1) + 1
        circuit_lists, exponent_lists, ideal_outs = [], [], []
        if mode == 'reduced':
            shared_draws = []
            for j in range(circuits_per_depth):
                draws = [int(m) for m in rand_state.randint(0, group_order, num_projection_rounds)]
                if num_projection_rounds > 0:
                    draws[-1] = (j - sum(draws[:-1])) % group_order  # total draws = j (mod N)
                shared_draws.append(draws)
        for k in depths:
            circuits_at_depth, exponents_at_depth = [], []
            for j in range(circuits_per_depth):
                if mode == 'reduced':
                    # residues of k + sum(draws) still cycle with j at fixed k
                    draws = list(shared_draws[j])
                    total = k + sum(draws)
                elif mode == 'exact':
                    draws = [j]  # j IS the total random power; weighted by q(j) later
                    total = k + j
                else:
                    draws = [int(m) for m in rand_state.randint(0, group_order, k)]
                    draws[-1] = (j - sum(draws[:-1])) % group_order
                    total = sum(draws)
                circ = prep_fiducial + germ * total + meas_fiducial
                circuits_at_depth.append(circ)
                exponents_at_depth.append(draws)
            circuit_lists.append(circuits_at_depth)
            exponent_lists.append(exponents_at_depth)
            ideal_outs.append([success_outcome] * circuits_per_depth)

        # Pair the random exponents with circuit data so that they serialize/truncate properly
        self.paired_with_circuit_attrs = ["exponent_lists"]

        super().__init__(depths, circuit_lists, ideal_outs, qubit_labels, remove_duplicates=False)
        self.exponent_lists = exponent_lists
        self.germ = germ
        self.prep_fiducial = prep_fiducial
        self.meas_fiducial = meas_fiducial
        self.group_order = group_order
        self.irrep_index = irrep_index
        self.circuits_per_depth = circuits_per_depth
        self.mode = mode
        self.num_projection_rounds = num_projection_rounds
        self.descriptor = descriptor
        self.auxfile_types['germ'] = 'circuit-str-json'
        self.auxfile_types['prep_fiducial'] = 'circuit-str-json'
        self.auxfile_types['meas_fiducial'] = 'circuit-str-json'

    def total_germ_powers(self):
        """
        The total (random plus deterministic) germ power of each circuit.

        Returns
        -------
        list of lists of int
            One list per depth, in the same order as `circuit_lists`.
        """
        totals = []
        for k, exponents_at_depth in zip(self.depths, self.exponent_lists):
            offset = 0 if (self.mode == 'full') else k
            totals.append([offset + sum(draws) for draws in exponents_at_depth])
        return totals

    def character_weights(self):
        """
        The character weight `conj(chi_irrep(n))` of each circuit.

        Here `n` is the circuit's total germ power (mod the group order).
        Weighting each circuit's success probability by this value and
        averaging over circuits at fixed depth yields the character-weighted
        signal `z(k)` that cGST fits.  Note the weight includes the
        *deterministic* germ repetitions in 'reduced' mode, which cancels the
        ideal germ's phase so that fitted phases are directly the germ's
        coherent (over-rotation) angle deviation.

        In 'exact' mode the character values additionally carry the quadrature
        weights: circuit `j` at each depth (whose total random power is `j`) is
        weighted by `M * q(j) * conj(chi(n))`, where `q` is the exact
        distribution of the total of `num_projection_rounds` uniform draws and
        `M` the number of circuits per depth -- so that the plain average of
        `weight * probability` over a depth's circuits equals the synthetic
        projector's matrix element with zero sampling error.

        Returns
        -------
        list of numpy.ndarray
            One complex array per depth, in the same order as `circuit_lists`.
        """
        weights = [_ct.character_weights(self.group_order, self.irrep_index,
                                         [t % self.group_order for t in totals])
                   for totals in self.total_germ_powers()]
        if self.mode == 'exact':
            quad = _ct.uniform_power_distribution(self.group_order, self.num_projection_rounds)
            weights = [w * quad * len(quad) for w in weights]
        return weights


class CharacterGSTDesign(_proto.CombinedExperimentDesign):
    """
    A cGST experiment design: a collection of named :class:`CharacterGSTGermDesign` s.

    This is a thin :class:`CombinedExperimentDesign` marking its children as
    cGST germ-decay experiments, typically constructed with a helper such as
    :func:`create_1q_szy_cgst_design`.

    Parameters
    ----------
    germ_designs : dict
        A dictionary of :class:`CharacterGSTGermDesign` objects whose keys name
        each sub-experiment.

    qubit_labels : tuple, optional
        The qubits this experiment design applies to.

    germ_table : list, optional
        A machine-readable summary of the children, with one plain (JSON-able)
        dictionary per child holding the keys `'name'`, `'germ'` (circuit
        string), `'group_order'`, `'irrep_index'`, `'multiplicity'` (the
        dimension of the germ's eigenspace for that irrep), `'prep_fiducial'`
        and `'meas_fiducial'` (circuit strings), and `'pair_index'`.  Populated
        by :func:`pygsti.algorithms.cgstdesign.create_cgst_design`; `None` when
        the design was built by a helper that does not track this information.
    """

    def __init__(self, germ_designs, qubit_labels=None, germ_table=None):
        super().__init__(germ_designs, qubit_labels=qubit_labels)
        self.germ_table = None if (germ_table is None) else [dict(row) for row in germ_table]
        self.auxfile_types['germ_table'] = 'json'

    @property
    def germ_design_names(self):
        """The names of the germ-decay sub-designs (tuple of str)."""
        return tuple(self.keys())


def _ideal_circuit_ptm(circuit):
    """The ideal Pauli-transfer matrix of a 1Q circuit of standard-name gates."""
    std = _std_unitaries()
    ptm = _np.identity(4)
    for layer in circuit.layertup:
        ptm = _unitary_to_pauligate(std[layer.name]) @ ptm
    return ptm


def _select_fiducials(germ, group_order, irrep_index, gate_names, qubit_label, max_length=3):
    """
    Deterministically choose fiducial words maximizing the ideal cGST signal amplitude.

    Searches all words in `gate_names` up to `max_length`, preferring larger
    ideal amplitude (see :func:`pygsti.algorithms.cgstdesign._fiducial_overlap`),
    then shorter total length, then lexicographic order.  Returns
    `(prep_fiducial, meas_fiducial)` Circuits.

    The search itself is
    :func:`pygsti.algorithms.cgstdesign._select_fiducial_words`, which is also
    what the general-gate-set helper
    :func:`pygsti.algorithms.cgstdesign.select_cgst_fiducials` uses; this
    wrapper just supplies the one-qubit standard-gate-name superoperators.
    """
    germ_ptm = _ideal_circuit_ptm(germ)
    words = [()]
    for length in range(1, max_length + 1):
        words.extend(_itertools.product(gate_names, repeat=length))
    word_ptms = {}
    std = _std_unitaries()
    for word in words:
        ptm = _np.identity(4)
        for name in word:
            ptm = _unitary_to_pauligate(std[name]) @ ptm
        word_ptms[word] = ptm

    (best,) = _cgstdesign._select_fiducial_words(germ_ptm, group_order, irrep_index,
                                                 words, word_ptms, num_pairs=1)

    line_labels = (qubit_label,)
    return (_Circuit([(name, qubit_label) for name in best[0]], line_labels=line_labels),
            _Circuit([(name, qubit_label) for name in best[1]], line_labels=line_labels))


def create_1q_szy_cgst_design(depths, circuits_per_depth, mode='reduced',
                              num_projection_rounds=4, include_idle=True,
                              qubit_labels=('Q0',), seed=None):
    """
    The cGST experiment design for the one-qubit {S, sqrt(Y)} gate set.

    Builds the germ-decay sub-experiments that jointly amplify every error
    parameter of the {S, sqrt(Y)} gate set, with `S = Gzpi2` and
    `sqrt(Y) = Gypi2` (plus, optionally, idle-interleaved variants using `Gi`):

    * `'s_t1'`, `'s_ramsey'` : trivial- and complex-irrep decays of the S germ
      (`Z_4` group), giving S's parallel/orthogonal stochastic decays
      (`lambda1`, `lambda2`) and over-rotation angle `theta`.
    * `'y_t1'`, `'y_ramsey'` : the same for sqrt(Y) (`r1`, `r2`, `alpha`).
    * `'tri_t1'`, `'tri_ramsey'` : decays of the "triangle" germ `S*sqrt(Y)`
      (`Z_3` group), whose eigenvalues mix the two gates' errors and expose
      their *relational* errors (angle-between-axes `beta`, correlated
      stochastic and active error sums).
    * `'idle_s'`, `'idle_y'`, `'idle_tri'` : idle-interleaved germs isolating
      the idle gate's coherent error components by comparison with the bare
      germs' phases (only when `include_idle` is True).

    Fiducials are selected automatically (deterministically) to maximize the
    ideal decay-signal amplitude using only the native gates.

    Parameters
    ----------
    depths : list of ints
        The germ depths (see :class:`CharacterGSTGermDesign`).

    circuits_per_depth : int
        The number of randomized circuits at each depth of each sub-experiment.

    mode : {'reduced', 'full', 'exact'}, optional
        The cGST sampling mode (see the module docstring of
        :mod:`pygsti.protocols.cgst`).

    num_projection_rounds : int, optional
        The number of random projection rounds in 'reduced' mode.

    include_idle : bool, optional
        Whether to include the idle-characterization sub-experiments.

    qubit_labels : tuple, optional
        A 1-tuple of the qubit label to use.

    seed : int, optional
        Base seed for the random germ powers (each sub-design gets a distinct
        derived seed).

    Returns
    -------
    CharacterGSTDesign
    """
    assert len(qubit_labels) == 1, "This is a one-qubit experiment design"
    q = qubit_labels[0]
    lbls = (q,)

    def circ(*gate_names):
        return _Circuit([(name, q) for name in gate_names], line_labels=lbls)

    # (name, germ, group order, irrep index)
    specs = [('s_t1', circ('Gzpi2'), 4, 0),
             ('s_ramsey', circ('Gzpi2'), 4, 1),
             ('y_t1', circ('Gypi2'), 4, 0),
             ('y_ramsey', circ('Gypi2'), 4, 1),
             ('tri_t1', circ('Gzpi2', 'Gypi2'), 3, 0),
             ('tri_ramsey', circ('Gzpi2', 'Gypi2'), 3, 1)]
    if include_idle:
        specs += [('idle_s', circ('Gzpi2', 'Gi'), 4, 1),
                  ('idle_y', circ('Gypi2', 'Gi'), 4, 1),
                  ('idle_tri', circ('Gzpi2', 'Gypi2', 'Gi'), 3, 1)]

    designs = {}
    for i, (name, germ, order, irrep) in enumerate(specs):
        prep_fid, meas_fid = _select_fiducials(germ, order, irrep, ('Gzpi2', 'Gypi2'), q)
        designs[name] = CharacterGSTGermDesign(
            germ, order, irrep, depths, circuits_per_depth,
            prep_fiducial=prep_fid, meas_fiducial=meas_fid, mode=mode,
            num_projection_rounds=num_projection_rounds, qubit_labels=lbls,
            seed=None if (seed is None) else seed + i,
            descriptor="cGST '%s' experiment for the 1Q {S, sqrt(Y)} gate set" % name)
    return CharacterGSTDesign(designs, qubit_labels=lbls)


def true_germ_eigenvalues(model, germ, group_order):
    """
    Numerically extract a noisy germ's eigenvalue deviations, per irrep, from a model.

    The dense superoperator of `germ` under `model` is eigendecomposed and each
    eigenvalue is matched to the ideal irrep phase `exp(2j*pi*irrep/group_order)`
    it is closest to (in angle).  The returned deviations are gauge-invariant
    ground truth for what cGST's decay fits estimate: magnitude = stochastic
    decay, phase = coherent angle error.  For the trivial irrep the
    trace-preserving fixed point (eigenvalue exactly 1) is excluded.

    Parameters
    ----------
    model : Model
        The (noisy) model to extract eigenvalues from.  Must be simulable with
        a matrix forward simulator (e.g. an :class:`ExplicitOpModel`).

    germ : Circuit
        The germ circuit.

    group_order : int
        The order of the cyclic group generated by the ideal germ.

    Returns
    -------
    dict
        Maps irrep index to the complex eigenvalue deviation `y` (noisy
        eigenvalue times the conjugated ideal phase).  Irreps on which the
        ideal germ has no support are absent.
    """
    noisy_ptm = model.sim.product(germ)
    evals = _np.linalg.eigvals(noisy_ptm)
    out = {}
    for irrep in range(group_order):
        ideal_phase = _np.exp(2j * _np.pi * irrep / group_order)
        deviations = evals * _np.conj(ideal_phase)
        candidates = [d for d in deviations
                      if abs(_np.angle(d)) < _np.pi / group_order and abs(d) > 1e-6]
        if irrep == 0 and len(candidates) > 1:
            # drop the TP fixed point (the eigenvalue closest to exactly 1)
            candidates = sorted(candidates, key=lambda d: abs(d - 1.0))[1:]
        elif irrep == 0:
            continue  # only the fixed point lives here: no decaying branch
        if candidates:
            out[irrep] = max(candidates, key=abs)
    return out


def _to_json_safe(obj):
    """Recursively convert numpy scalars/arrays in dicts to plain python types."""
    if isinstance(obj, dict):
        return {k: _to_json_safe(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_to_json_safe(v) for v in obj]
    if isinstance(obj, _np.ndarray):
        return _to_json_safe(obj.tolist())
    if isinstance(obj, (_np.floating, _np.integer)):
        return obj.item()
    if isinstance(obj, (complex, _np.complexfloating)):
        return [float(_np.real(obj)), float(_np.imag(obj))]
    return obj


def _gate_label_to_str(gate):
    """
    Render a gate reference as a string, so that it survives JSON serialization.

    :class:`~pygsti.baseobjs.Label` objects (and label tuples) are converted with
    `str`, which produces e.g. `'Gzpi2:Q0'`; both that and a bare gate name are
    resolved back to a model's operation label by
    :func:`pygsti.algorithms.cgstgauge.standard_gauge_transform`.
    """
    if gate is None or isinstance(gate, str):
        return gate
    if isinstance(gate, (_Label, tuple)):
        return str(_Label(gate))
    raise TypeError("A gate reference must be a string, Label or label tuple, not %s"
                    % type(gate).__name__)


class CharacterDecayResults(_proto.ProtocolResults):
    """
    The results of running :class:`CharacterDecay` on one cGST germ-decay experiment.

    Attributes of note: `depths`, `signal` (the complex character-weighted
    probabilities `z(k)`), `fit` (the decay-fit parameter dictionary),
    `germ_eigenvalue_magnitude` and `germ_eigenvalue_phase` (the estimated
    noisy-germ eigenvalue deviation on the targeted irrep's branch, after
    inversion of the Fourier-operator eigenvalue map when the data was taken
    in 'full' mode).

    Parameters
    ----------
    data : ProtocolData
        The experimental data these results are generated from.

    protocol_instance : Protocol
        The protocol that generated these results.

    signal : numpy.ndarray
        The character-weighted signal `z(k)`, one complex value per depth.

    fit : dict
        The fit dictionary from :func:`pygsti.algorithms.cgstfit.fit_real_decay`
        or :func:`~pygsti.algorithms.cgstfit.fit_complex_decay`.

    germ_eigenvalue : complex
        The estimated germ eigenvalue deviation.
    """

    def __init__(self, data, protocol_instance, signal, fit, germ_eigenvalue):
        super().__init__(data, protocol_instance)
        design = data.edesign
        self.depths = list(design.depths)
        self.irrep_index = design.irrep_index
        self.group_order = design.group_order
        self.mode = design.mode
        self.signal_real = [float(v) for v in _np.real(signal)]
        self.signal_imag = [float(v) for v in _np.imag(signal)]
        self.fit = _to_json_safe(fit)
        self.germ_eigenvalue_magnitude = float(_np.abs(germ_eigenvalue))
        self.germ_eigenvalue_phase = float(_np.angle(germ_eigenvalue))

    @property
    def signal(self):
        """The complex character-weighted signal `z(k)` (numpy.ndarray)."""
        return _np.array(self.signal_real) + 1j * _np.array(self.signal_imag)

    @property
    def germ_eigenvalue(self):
        """The estimated complex germ eigenvalue deviation on the targeted irrep branch."""
        return self.germ_eigenvalue_magnitude * _np.exp(1j * self.germ_eigenvalue_phase)

    def plot(self, ax=None, title=None):
        """
        Plot the character-weighted decay data and fit.

        Plots `|z(k)|` with the fitted decay curve and, for Ramsey-type
        (complex-irrep) data, the unwrapped phase and its linear fit on a twin
        axis.

        Parameters
        ----------
        ax : matplotlib.axes.Axes, optional
            An axis to plot on (a new figure is created if None).

        title : str, optional
            A title for the plot.

        Returns
        -------
        matplotlib.axes.Axes
        """
        try:
            import matplotlib.pyplot as _plt
        except ImportError:
            raise ValueError("This function requires you to install matplotlib!")

        if ax is None:
            _, ax = _plt.subplots(figsize=(5, 3.5))
        depths = _np.array(self.depths, dtype=float)
        fine = _np.linspace(depths.min(), depths.max(), 200)
        est = self.fit['estimates']

        if self.irrep_index == 0:
            ax.plot(depths, self.signal_real, 'o', label='data')
            ax.plot(fine, (est['B'] - est['C']) * est['lam'] ** fine + est['C'],
                    '-', label='fit: $\\lambda$=%.4f' % est['lam'])
            ax.set_ylabel('$z(k)$')
        else:
            ax.plot(depths, _np.abs(self.signal), 'o', label='|z| data')
            ax.plot(fine, est['A'] * est['lam'] ** fine, '-',
                    label='fit: $\\lambda$=%.4f' % est['lam'])
            ax.set_ylabel('$|z(k)|$')
            ax2 = ax.twinx()
            ax2.plot(depths, _np.unwrap(_np.angle(self.signal)), 's', color='tab:red',
                     alpha=0.6, label='phase data')
            ax2.plot(fine, est['theta'] * fine + est['phi'], '--', color='tab:red',
                     label='fit: $\\theta$=%.2e' % est['theta'])
            ax2.set_ylabel('phase (rad)', color='tab:red')
        ax.set_xlabel('germ depth $k$')
        ax.legend(loc='best', fontsize=8)
        if title:
            ax.set_title(title)
        return ax


class CharacterDecay(_proto.Protocol):
    """
    The analysis protocol for a single cGST germ-decay experiment.

    Computes the character-weighted signal `z(k)` from the data, fits the
    appropriate single-exponential decay model (real with asymptote for the
    trivial irrep; complex with phase winding otherwise), and -- for data
    taken in 'full' sampling mode -- numerically inverts the Fourier-operator
    eigenvalue map to report a bare germ eigenvalue.

    Parameters
    ----------
    bootstrap_samples : int, optional
        The number of residual-bootstrap resamples used for error bars
        (0 disables bootstrapping).

    invert_full_mode : bool, optional
        Whether to invert full-mode fitted decays into bare germ eigenvalues.

    seed : int, optional
        Seed for the bootstrap resampling.

    name : str, optional
        The name of this protocol.
    """

    def __init__(self, bootstrap_samples=0, invert_full_mode=True, seed=None, name=None):
        super().__init__(name)
        self.bootstrap_samples = bootstrap_samples
        self.invert_full_mode = invert_full_mode
        self.seed = seed

    def run(self, data, memlimit=None, comm=None):
        """
        Run this protocol on `data`.

        Parameters
        ----------
        data : ProtocolData
            The input data.  Its experiment design must be a
            :class:`CharacterGSTGermDesign`.

        memlimit : int, optional
            A rough per-processor memory limit in bytes (unused).

        comm : mpi4py.MPI.Comm, optional
            An MPI communicator (unused).

        Returns
        -------
        CharacterDecayResults
        """
        design = data.edesign
        assert isinstance(design, CharacterGSTGermDesign), \
            "This protocol can only be run on a CharacterGSTGermDesign"
        ds = data.dataset

        signal = []
        for circuits, weights, idealouts in zip(design.circuit_lists, design.character_weights(),
                                                design.idealout_lists):
            values = [w * ds[c].counts.get((out,), 0.0) / ds[c].total
                      for c, w, out in zip(circuits, weights, idealouts)]
            signal.append(_np.mean(values))
        signal = _np.array(signal)

        rand_state = _np.random.RandomState(self.seed)
        if design.irrep_index == 0:
            fit = _cgstfit.fit_real_decay(design.depths, signal.real,
                                          bootstrap_samples=self.bootstrap_samples,
                                          rand_state=rand_state)
            eigenvalue = complex(fit['estimates']['lam'])
        else:
            fit = _cgstfit.fit_complex_decay(design.depths, signal,
                                             bootstrap_samples=self.bootstrap_samples,
                                             rand_state=rand_state)
            eigenvalue = fit['estimates']['lam'] * _np.exp(1j * fit['estimates']['theta'])

        if design.mode == 'full' and self.invert_full_mode:
            eigenvalue = _cgstfit.invert_projector_eigenvalue(eigenvalue, design.group_order)

        return CharacterDecayResults(data, self, signal, fit, eigenvalue)


def extract_szy_error_parameters(decay_results):
    """
    Invert 1Q {S, sqrt(Y)} cGST decay fits into standard-gauge error parameters.

    Implements (to first order in the error rates) the closed-form parameter
    extraction for the gate set built by :func:`create_1q_szy_cgst_design`.
    Intrinsic parameters come directly from the single-germ decays; relational
    parameters come from the triangle-germ ("triangle equations") and
    idle-interleaved decays combined with the single-germ results.

    The parameters are those of the standard-gauge error channels.  In the
    Pauli basis (I, X, Y, Z), S's error channel is

        E_S = [[     1,                  0,                   0,  0      ],
               [     0,  lambda2*cos(theta), -lambda2*sin(theta),  0      ],
               [     0,  lambda2*sin(theta),  lambda2*cos(theta),  0      ],
               [    -a,                  0,                   0,  lambda1]]

    -- an over-rotation `theta` about Z, a decay `lambda1` along the rotation
    axis and `lambda2` in the equatorial plane, and an active
    (amplitude-damping-type) shift `a` along Z.  The noisy gate is
    `E_S @ R_z(pi/2)`.

    The noisy sqrt(Y) is `R_x(beta) @ E_sto @ R_y(pi/2 + alpha) @ R_x(-beta)`,
    where `alpha` is its over-rotation, `beta` is the angle between the two
    gates' rotation axes (the relational coherent error, placed along X by the
    standard gauge), and

        E_sto = [[    1,     0,     0,     0 ],
                 [a_rel, 1 - r2,  c_xy,  c_xz],
                 [ a_y,   c_xy, 1 - r1,  c_yz],
                 [a_rel,  c_xz,  c_yz, 1 - r2]]

    so `r1` is the stochastic decay along sqrt(Y)'s own (Y) axis and `r2` the
    decay of the two orthogonal components, `a_y` and `a_rel` are its axial and
    relational active errors, and `c_xy`, `c_xz`, `c_yz` are the correlated
    stochastic rates.

    Parameters
    ----------
    decay_results : dict
        Maps the sub-experiment names produced by
        :func:`create_1q_szy_cgst_design` to their
        :class:`CharacterDecayResults`.  The idle entries are optional.

    Returns
    -------
    dict
        Error parameters; all angles in radians.  Keys include `'theta'`,
        `'alpha'` (S / sqrt(Y) over-rotations), `'lambda1'`, `'lambda2'`
        (S's decay eigenvalues), `'r1'`, `'r2'` (sqrt(Y)'s decay rates),
        `'a'` (S's active/asymptote error), `'beta'` (angle between gate
        axes), `'c_sum'` (the correlated-stochastic-error sum
        `c_xy + c_xz + c_yz`), `'active_combo'` (the relational active-error
        combination `-a + a_y + 2*a_rel`), and -- when idle experiments are
        present -- `'theta_idle_x/y/z'` and `'idle_decay_excess_*'`.
    """
    def mag(name): return decay_results[name].germ_eigenvalue_magnitude
    def phase(name): return decay_results[name].germ_eigenvalue_phase
    def asymptote(name): return decay_results[name].fit['estimates']['C']

    params = {}
    # -- intrinsic single-gate parameters (direct reads)
    params['theta'] = phase('s_ramsey')
    params['alpha'] = phase('y_ramsey')
    params['lambda1'] = mag('s_t1')
    params['lambda2'] = mag('s_ramsey')
    # r1/r2 are defined OPERATIONALLY as sqrt(Y)'s eigenvalue deficits: r1 on
    # the branch parallel to its rotation axis, r2 on the orthogonal (Ramsey)
    # branches.  (At first order these are combinations of the entries of
    # sqrt(Y)'s stochastic block E_sto, with r1 built from the rate along the
    # rotation axis and r2 from the two orthogonal ones.)
    params['r1'] = 1.0 - mag('y_t1')
    params['r2'] = 1.0 - mag('y_ramsey')
    # S's active (amplitude-damping-type) error from the T1 asymptote.  In the
    # standard-gauge form of the S error channel the active shift sits in the Z
    # row of the affine column, E_S[3, 0] = -a, so the trivial-irrep signal
    # decays to C = 1/2 - a/(2(1-lambda1)) and hence a = (1-lambda1)(1-2C).
    params['a'] = (1.0 - params['lambda1']) * (1.0 - 2.0 * asymptote('s_t1'))

    # -- relational parameters from the triangle germ (Z3), first order.
    # The character weighting cancels the ideal 2*pi/3 phase, so the fitted
    # triangle phase is directly omega - 2*pi/3 = (theta + alpha + 2*beta)/sqrt(3).
    delta_omega = phase('tri_ramsey')
    params['omega_deviation'] = delta_omega
    params['beta'] = (_np.sqrt(3.0) * delta_omega - params['theta'] - params['alpha']) / 2.0
    # Correlated-stochastic sum from the splitting of the triangle's decay
    # eigenvalues.  The triangle germ rotates about (X+Y+Z)/sqrt(3), which
    # weights the three correlated rates equally: at first order the trivial
    # branch is shifted by +(2/3)*c_sum and the complex branches by
    # -(1/3)*c_sum, so the splitting is exactly
    #   lam1_tri - lam2_tri = c_xy + c_xz + c_yz.
    lam1_tri, lam2_tri = mag('tri_t1'), mag('tri_ramsey')
    params['lambda1_triangle'] = lam1_tri
    params['lambda2_triangle'] = lam2_tri
    params['c_sum'] = lam1_tri - lam2_tri
    # Relational active-error combination from the triangle T1 asymptote.  The
    # fixed-point shift of the triangle germ (with the inter-gate rotation of
    # S's shift vector accounted for) gives, at first order,
    #   -a + a_y + 2*a_rel = 3 * (1 - lam1_tri) * (2*C_tri - 1).
    # The minus sign on `a` is because sqrt(Y) rotates S's active shift from
    # the z axis onto the x axis before it is projected onto the triangle axis
    # (x + y + z)/sqrt(3).
    params['active_combo'] = 3.0 * (1.0 - lam1_tri) * (2.0 * asymptote('tri_t1') - 1.0)

    # -- idle characterization: interleaved-vs-bare phase differences give the
    # idle's coherent error components along each probed axis.
    if 'idle_s' in decay_results:
        params['theta_idle_z'] = phase('idle_s') - params['theta']
        params['theta_idle_y'] = phase('idle_y') - params['alpha']
        delta_tri_idle = phase('idle_tri') - delta_omega
        # the triangle axis is (X+Y+Z)/sqrt(3), so the idle's contribution to
        # the interleaved-triangle phase is (thIx + thIy + thIz)/sqrt(3)
        params['theta_idle_x'] = (_np.sqrt(3.0) * delta_tri_idle
                                  - params['theta_idle_y'] - params['theta_idle_z'])
        for germ_name, bare in [('idle_s', 's_ramsey'), ('idle_y', 'y_ramsey'),
                                ('idle_tri', 'tri_ramsey')]:
            params['idle_decay_excess_' + germ_name[5:]] = 1.0 - mag(germ_name) / mag(bare)
    return params


class CharacterGSTResults(_proto.ProtocolResults):
    """
    The results of running the :class:`CharacterGST` protocol.

    Holds a summary of every germ-decay fit (the per-experiment results
    themselves are stored as children of the returned results directory) and,
    when a gate-set-specific inversion was requested, the extracted error
    parameters.

    Parameters
    ----------
    data : ProtocolData
        The experimental data these results are generated from.

    protocol_instance : Protocol
        The protocol that generated these results.

    decay_summaries : dict
        Maps sub-experiment name to a small dict of its fitted decay values.

    error_parameters : dict or None
        The extracted error parameters (see
        :func:`extract_szy_error_parameters`), if a `'szy'` inversion was
        performed.

    errorgen_estimates : dict, optional
        The standard-gauge elementary error generator coefficients estimated by
        the `'linear'` gate-set inversion: maps a gate label (as a string) to a
        dict mapping an error generator label (as a string) to a
        `{'value': float, 'stderr': float}` dictionary.  `None` when no linear
        inversion was performed.

    estimated_model : Model, optional
        The estimated gate set, in the cGST standard gauge (see
        :func:`pygsti.algorithms.cgstgauge.fix_standard_gauge`).  `None` when
        no linear inversion was performed.

    inversion_info : dict, optional
        Diagnostics of the linear inversion, with keys `'rank'` (the numerical
        rank of the design matrix, i.e. the number of error generator
        directions the design amplifies), `'num_params'`, `'num_observables'`,
        `'num_unamplified'` (the dimension of the design matrix's null space),
        `'residual_norm'` (the norm of the unexplained part of the observables),
        `'singular_values'` (a list) and `'skipped_children'` (the names of the
        sub-experiments the inversion could not use).
    """

    def __init__(self, data, protocol_instance, decay_summaries, error_parameters,
                 errorgen_estimates=None, estimated_model=None, inversion_info=None):
        super().__init__(data, protocol_instance)
        self.decay_summaries = _to_json_safe(decay_summaries)
        self.error_parameters = _to_json_safe(error_parameters)
        self.errorgen_estimates = _to_json_safe(errorgen_estimates)
        self.estimated_model = estimated_model
        self.inversion_info = _to_json_safe(inversion_info)
        self.auxfile_types['estimated_model'] = 'serialized-object'

    def to_dataframe(self):
        """
        Tabulate these results as a pandas DataFrame.

        One row per germ-decay sub-experiment (eigenvalue magnitude/phase and
        uncertainties), followed by one row per extracted error parameter
        (`'szy'` inversion) and one row per standard-gauge error generator
        coefficient (`'linear'` inversion).

        Returns
        -------
        pandas.DataFrame
        """
        import pandas as _pd
        rows = []
        for name, summ in self.decay_summaries.items():
            rows.append({'quantity': name, 'type': 'decay',
                         'magnitude': summ['magnitude'], 'phase': summ['phase'],
                         'magnitude_stderr': summ.get('magnitude_stderr'),
                         'phase_stderr': summ.get('phase_stderr')})
        if self.error_parameters:
            for key, val in self.error_parameters.items():
                rows.append({'quantity': key, 'type': 'error parameter', 'value': val})
        if self.errorgen_estimates:
            for gate, per_gate in self.errorgen_estimates.items():
                for egl, entry in per_gate.items():
                    rows.append({'quantity': '%s:%s' % (gate, egl), 'type': 'error generator',
                                 'value': entry['value'], 'stderr': entry['stderr']})
        return _pd.DataFrame(rows)


def _design_fingerprint(design):
    """
    A hashable summary of everything about `design` that its design matrix depends on.

    Besides each child's germ, irrep, fiducials, depths and sampling mode this
    includes a digest of its *realized* random germ powers (`exponent_lists`):
    two `'reduced'`-mode designs that differ only in their seeds produce
    different decay curves, and hence different finite-differenced Jacobians.
    """
    parts = []
    for name in design.keys():
        child = design[name]
        exponents = _hashlib.sha1(repr([[list(map(int, d)) for d in per_depth]
                                        for per_depth in child.exponent_lists]).encode()).hexdigest()
        parts.append((str(name), child.germ.str, int(child.group_order), int(child.irrep_index),
                      str(child.mode), int(child.num_projection_rounds),
                      tuple(int(d) for d in child.depths), int(child.circuits_per_depth),
                      child.prep_fiducial.str, child.meas_fiducial.str, exponents))
    return tuple(parts)


def _model_fingerprint(model):
    """A hashable summary of a (target) model's dense operations, preps and POVM effects."""
    def _bytes(obj):
        return _np.ascontiguousarray(obj.to_dense(), dtype='d').tobytes()
    try:
        ops = tuple((str(lbl), _bytes(op)) for lbl, op in model.operations.items())
        preps = tuple((str(lbl), _bytes(prep)) for lbl, prep in model.preps.items())
        povms = tuple((str(plbl), tuple((str(elbl), _bytes(effect))
                                        for elbl, effect in povm.items()))
                      for plbl, povm in model.povms.items())
        return (ops, preps, povms)
    except Exception:  # pragma: no cover - defensive: fall back to object identity
        return id(model)


class CharacterGST(_proto.Protocol):
    """
    The character gate set tomography protocol.

    Runs :class:`CharacterDecay` on every sub-experiment of a
    :class:`CharacterGSTDesign` and, optionally, inverts the collection of
    fitted decays into gate-set error parameters.

    Two inversions are available.  The `'szy'` one is the closed-form
    parameter extraction for the one-qubit {S, sqrt(Y)} gate set (see
    :func:`extract_szy_error_parameters`).  The
    `'linear'` one is generic: it solves the first-order linear system relating
    the fitted decays to the gates' elementary error generator coefficients
    (see :mod:`pygsti.algorithms.cgstinversion`), and reports the resulting
    gate set and its error generator coefficients in the cGST standard gauge
    (see :mod:`pygsti.algorithms.cgstgauge`).

    Parameters
    ----------
    bootstrap_samples : int, optional
        The number of bootstrap resamples for per-fit error bars.  These are
        also what the `'linear'` inversion propagates into error bars on the
        reported error generator coefficients, so a nonzero value is needed
        for meaningful uncertainties.

    gateset_inversion : {None, 'szy', 'linear'}, optional
        Which gate-set inversion to run in addition to the per-germ decay fits.
        `'szy'` requires the design to have been built by
        :func:`create_1q_szy_cgst_design`; `'linear'` requires `target_model`
        and `reference_gate`.

    target_model : Model, optional
        The ideal gate set (needed by, and only used by, the `'linear'`
        inversion).  Must be an explicit model in the `'pp'` basis that
        supports `set_all_parameterizations('GLND')` and a matrix forward
        simulator, e.g. one built by
        :func:`pygsti.models.modelconstruction.create_explicit_model`.

    reference_gate : str or Label, optional
        The gate brought to the commuting gauge when fixing the standard gauge
        (the S gate, `'Gzpi2'`, for the {S, sqrt(Y)} gate set).  Required for
        `'linear'`.

    other_gates : list, optional
        The gates whose errors are minimized by the second stage of the
        standard-gauge construction.  `None` (the default) uses every gate of
        the target model other than the reference gate.

    design_matrix_step : float, optional
        The finite-difference step used to build the first-order design matrix
        (see :func:`pygsti.algorithms.cgstinversion.first_order_design_matrix`).

    rcond : float, optional
        The relative singular-value cutoff used to determine the rank of the
        design matrix and to solve the linear system.  Because the design
        matrix is built from finite differences of *fitted* decay rates its
        numerically-zero singular values sit well above machine precision, so
        the default is much larger than a typical least-squares `rcond`.

    seed : int, optional
        Seed for bootstrap resampling.

    name : str, optional
        The name of this protocol.

    Notes
    -----
    The design matrix depends only on the experiment design and the target
    model, so it is computed once and cached (in a class-level dictionary that
    is not serialized with the protocol) across protocol instances.
    """

    #: Cache of `(jacobian, ideal observables)` keyed by design/target/step, shared
    #: by all instances.  This is a class attribute (not an instance one) precisely
    #: so that it is not part of `self.__dict__` and hence never serialized.
    _design_matrix_cache = {}

    #: The most design matrices to keep cached at once.
    _design_matrix_cache_size = 8

    def __init__(self, bootstrap_samples=200, gateset_inversion=None, target_model=None,
                 reference_gate=None, other_gates=None, design_matrix_step=1e-4,
                 rcond=1e-4, seed=None, name=None):
        super().__init__(name)
        if gateset_inversion not in (None, 'szy', 'linear'):
            raise ValueError("gateset_inversion must be None, 'szy' or 'linear', not %s"
                             % repr(gateset_inversion))
        if gateset_inversion == 'linear':
            if target_model is None:
                raise ValueError("gateset_inversion='linear' requires a `target_model` "
                                 "(the ideal gate set the error generators are defined "
                                 "relative to)")
            if reference_gate is None:
                raise ValueError("gateset_inversion='linear' requires a `reference_gate` "
                                 "(the gate brought to the commuting gauge when fixing the "
                                 "standard gauge, e.g. 'Gzpi2')")
        self.bootstrap_samples = bootstrap_samples
        self.gateset_inversion = gateset_inversion
        self.target_model = target_model
        # keep the gate references JSON-serializable (a Label round-trips through str)
        self.reference_gate = _gate_label_to_str(reference_gate)
        self.other_gates = None if (other_gates is None) else \
            [_gate_label_to_str(g) for g in other_gates]
        self.design_matrix_step = design_matrix_step
        self.rcond = rcond
        self.seed = seed
        self.auxfile_types['target_model'] = 'serialized-object'

    def _cached_design_matrix(self, design, obs_labels):
        """
        The first-order design matrix and ideal observables for `design`, memoized.

        Keyed by the design's germ/fiducial/depth structure, the target model's
        operations and the finite-difference step, so that repeated runs (and
        runs of separate protocol instances) on the same design reuse the -- by
        far most expensive -- Jacobian computation.
        """
        key = (_design_fingerprint(design), _model_fingerprint(self.target_model),
               float(self.design_matrix_step))
        cache = CharacterGST._design_matrix_cache
        if key not in cache:
            if len(cache) >= CharacterGST._design_matrix_cache_size:
                cache.pop(next(iter(cache)))
            jacobian = _cgstinversion.first_order_design_matrix(
                self.target_model, design, step=self.design_matrix_step, obs_labels=obs_labels)
            y_ideal = _cgstinversion.simulate_observables(
                self.target_model, design, self.target_model, obs_labels=obs_labels)
            cache[key] = (jacobian, y_ideal)
        return cache[key]

    def _linear_inversion(self, design, decays):
        """
        Estimate standard-gauge error generator coefficients from fitted decays.

        Solves the first-order linear system `J x = y - y_ideal` for the
        minimum-norm error generator coefficient vector `x`, builds the
        corresponding gate set, fixes the standard gauge, and reads off the
        gauge-fixed elementary error generator coefficients.  Uncertainties are
        obtained by propagating the observables' standard errors through this
        entire (cheap, and nearly linear) map by central finite differences.

        The least-squares solve itself is deliberately *unweighted*.  The
        observables' standard errors span several orders of magnitude (a phase
        fitted over 128 germ repetitions is far better determined than a
        trivial-block asymptote), and weighting by them rescales the rows of a
        design matrix whose smallest amplified singular value is already only
        ~1e-1 of the largest, which makes the numerical rank -- a property of
        the *design*, not of the data -- depend on the noise realization.
        Leaving the solve unweighted also makes `y -> coefficients` a
        well-defined map, which is what the finite-difference error propagation
        below differentiates.

        Returns `(errorgen_estimates, estimated_model, inversion_info)`.
        """
        target = self.target_model
        _cgstinversion.check_design_modes(design)  # raises on 'full', warns on 'reduced'
        obs_labels = _cgstinversion.observable_labels(design, target)
        used = set(name for name, _ in obs_labels)
        skipped = [name for name in design.keys() if name not in used]
        if len(obs_labels) == 0:
            raise ValueError("This design provides no usable cGST observables: the linear "
                             "inversion has nothing to work with.")
        param_labels = _cgstinversion.errorgen_parameter_labels(target)
        jacobian, y_ideal = self._cached_design_matrix(design, obs_labels)
        y, y_stderr = _cgstinversion.observables_from_results(decays, design, target)

        def gauge_fixed_coefficients(observables):
            """The standard-gauge coefficient dict (and model, and solve info) for `y`."""
            solution = _cgstinversion.invert_first_order(observables, y_ideal, jacobian,
                                                         rcond=self.rcond)
            model = _cgstinversion.model_from_errorgen_coefficients(
                target, _cgstinversion.coefficients_to_dict(solution['coefficients'],
                                                            param_labels))
            gauged = _cgstgauge.fix_standard_gauge(model, target, self.reference_gate,
                                                   self.other_gates)
            return solution, gauged, _cgstgauge.errorgen_coefficients_in_gauge(gauged, target)

        solution, estimated_model, coefficients = gauge_fixed_coefficients(y)
        coeff_keys = [(gate, egl) for gate in coefficients for egl in coefficients[gate]]

        def flatten(gauge_coefficients):
            return _np.array([gauge_coefficients[gate][egl] for gate, egl in coeff_keys], 'd')

        values = flatten(coefficients)

        stderrs = self._propagate_uncertainties(y, y_stderr, gauge_fixed_coefficients,
                                                flatten, len(values))

        errorgen_estimates = {}
        for (gate, egl), value, stderr in zip(coeff_keys, values, stderrs):
            errorgen_estimates.setdefault(str(gate), {})[str(egl)] = \
                {'value': float(value), 'stderr': float(stderr)}

        singular_values = _np.asarray(solution['singular_values'], dtype='d')
        inversion_info = {
            'rank': int(solution['rank']),
            'num_params': len(param_labels),
            'num_observables': len(obs_labels),
            'num_unamplified': int(solution['unamplified_directions'].shape[1]),
            'residual_norm': float(_np.linalg.norm(solution['residual'])),
            'singular_values': [float(v) for v in singular_values],
            'skipped_children': skipped}
        return errorgen_estimates, estimated_model, inversion_info

    @staticmethod
    def _propagate_uncertainties(y, y_stderr, gauge_fixed_coefficients, flatten, num_coefficients):
        """
        Finite-difference propagation of observable uncertainties onto the coefficients.

        With `F[i, c] = d(coefficient c)/d(observable i)` and uncorrelated
        observables, `stderr_c**2 = sum_i (F[i, c] * sigma_i)**2`; each column
        of `F` is obtained by a central difference of the whole post-Jacobian
        pipeline (a linear solve plus a standard-gauge fit; the full
        propagation takes a couple of seconds for a one-qubit design, against
        tens of seconds for the Jacobian itself).  Missing or non-positive
        uncertainties are replaced by the median of the usable ones (with a
        warning), and if the pipeline fails for any perturbation the reported
        uncertainties are all NaN.
        """
        sigma = _np.array(y_stderr, dtype='d')
        good = _np.isfinite(sigma) & (sigma > 0)
        if not _np.any(good):
            _warnings.warn("cGST linear inversion: no usable observable uncertainties "
                           "(run with bootstrap_samples > 0 on sampled data); reporting NaN "
                           "error bars on the error generator coefficients.")
            return _np.full(num_coefficients, _np.nan)
        if not _np.all(good):
            _warnings.warn("cGST linear inversion: %d of %d observables have no usable "
                           "uncertainty; substituting the median of the others."
                           % (int(_np.sum(~good)), len(sigma)))
            sigma[~good] = _np.median(sigma[good])

        contributions = _np.zeros((len(sigma), num_coefficients), 'd')
        for i in range(len(sigma)):
            # differentiate with a step that is large enough to stay above the
            # gauge optimizer's convergence noise, then scale by sigma_i
            step = max(float(sigma[i]), 1e-6)
            try:
                plus = y.copy(); plus[i] += step
                minus = y.copy(); minus[i] -= step
                derivative = (flatten(gauge_fixed_coefficients(plus)[2])
                              - flatten(gauge_fixed_coefficients(minus)[2])) / (2 * step)
            except Exception as e:
                _warnings.warn("cGST linear inversion: uncertainty propagation failed while "
                               "perturbing observable %d (%s); reporting NaN error bars." % (i, e))
                return _np.full(num_coefficients, _np.nan)
            contributions[i, :] = derivative * sigma[i]
        return _np.sqrt(_np.sum(contributions ** 2, axis=0))

    def run(self, data, memlimit=None, comm=None):
        """
        Run this protocol on `data`.

        Parameters
        ----------
        data : ProtocolData
            The input data.  Its experiment design must be a
            :class:`CharacterGSTDesign` (or any combined design whose children
            are :class:`CharacterGSTGermDesign` objects).

        memlimit : int, optional
            A rough per-processor memory limit in bytes (unused).

        comm : mpi4py.MPI.Comm, optional
            An MPI communicator (unused).

        Returns
        -------
        ProtocolResultsDir
            With a :class:`CharacterGSTResults` at the top level and one
            :class:`CharacterDecayResults` child per sub-experiment.
        """
        design = data.edesign
        decay_protocol = CharacterDecay(bootstrap_samples=self.bootstrap_samples,
                                        seed=self.seed)
        decays, children, summaries = {}, {}, {}
        for name in design.keys():
            results = decay_protocol.run(data[name])
            decays[name] = results
            children[name] = _proto.ProtocolResultsDir(data[name], results)
            fit_stderrs = results.fit.get('bootstrap_stderrs') or results.fit['stderrs']
            summaries[name] = {
                'magnitude': results.germ_eigenvalue_magnitude,
                'phase': results.germ_eigenvalue_phase,
                'magnitude_stderr': fit_stderrs.get('lam'),
                'phase_stderr': fit_stderrs.get('theta')}

        error_parameters = None
        errorgen_estimates = estimated_model = inversion_info = None
        if self.gateset_inversion == 'szy':
            error_parameters = extract_szy_error_parameters(decays)
        elif self.gateset_inversion == 'linear':
            errorgen_estimates, estimated_model, inversion_info = \
                self._linear_inversion(design, decays)

        top_results = CharacterGSTResults(data, self, summaries, error_parameters,
                                          errorgen_estimates=errorgen_estimates,
                                          estimated_model=estimated_model,
                                          inversion_info=inversion_info)
        return _proto.ProtocolResultsDir(data, top_results, children=children)
