"""
Character phase estimation (CPE) protocol objects
"""
#***************************************************************************************************
# Copyright 2015, 2019, 2025 National Technology & Engineering Solutions of Sandia, LLC (NTESS).
# Under the terms of Contract DE-NA0003525 with NTESS, the U.S. Government retains certain rights
# in this software.
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.  You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0 or in the LICENSE file in the root pyGSTi directory.
#***************************************************************************************************

import argparse as _argparse
import collections as _collections

import numpy as _np

from pygsti.algorithms.robust_phase_estimation import RobustPhaseEstimation as _RPEAnalysis
from pygsti.circuits import Circuit as _Circuit
from pygsti.protocols import protocol as _proto
from pygsti.protocols.cgst import CharacterGSTGermDesign as _CharacterGSTGermDesign
from pygsti.protocols.cgst import _to_json_safe
from pygsti.tools import chartools as _ct
from pygsti.tools.optools import unitary_to_pauligate as _unitary_to_pauligate

# Character phase estimation (CPE) combines the character-projector state
# synthesis of cGST with the geometric depth schedule and window-selection
# analysis of robust phase estimation (RPE).
#
# RPE estimates one eigenphase difference of a repeated gate with
# Heisenberg-like scaling, but assumes the preparation and measurement confine
# the signal to a single coherence |E_a><E_b|: any support on other eigenstate
# pairs injects additional frequencies into the signal, and if large enough
# these break the per-generation window selection (uncertainty over WHICH
# eigenvalue difference is being estimated).  CPE removes that assumption: a
# fixed number k0 of uniformly random germ powers, character-weighted in
# post-processing, act as a synthetic preparation of guaranteed irrep purity
# (an approximate projector whose residual bias is O(infidelity**(k0/2)); see
# pygsti.protocols.cgst).  The character-filtered complex signal
#
#     z_j(k) = < conj(chi_j(n_total)) * P_success(k) >
#
# is then single-frequency by construction, its per-depth raw angles
# arg(z_j(k) * conj(z_j(0))) = k * delta_j (mod 2pi) are fed into the standard
# RPE unwinding, and one experiment yields every irrep's phase: the SAME
# circuits, reweighted with a different character, estimate a different
# eigenvalue difference.  Because the character weight is evaluated at the
# total germ power (random plus deterministic), the ideal germ phase cancels
# and delta_j is directly the DEVIATION of irrep j's eigenphase from ideal.
#
# The circuits use 'exact' cGST sampling: for a cyclic germ the k0 random
# rounds are replaced by deterministic quadrature over the total random power,
# so the synthetic projector is evaluated with zero character-sampling error.


class CharacterPhaseEstimationDesign(_CharacterGSTGermDesign):
    """
    A CPE experiment: one germ, one fiducial pair, geometric depths, many irreps.

    This is a :class:`~pygsti.protocols.cgst.CharacterGSTGermDesign` in 'exact'
    sampling mode whose depth schedule satisfies the RPE doubling requirement
    and which targets a *collection* of irreps: the same circuits are
    reweighted per irrep in post-processing.

    Parameters
    ----------
    germ : Circuit
        The germ circuit.  Its ideal implementation must generate a cyclic
        group: `germ**group_order` must be the identity.

    group_order : int
        The order of the cyclic group generated by the ideal germ.

    irrep_indices : tuple of ints
        The irreps of `Z_group_order` whose eigenphase deviations to estimate.
        Each must label a *singly occupied* (non-degenerate) branch of the
        germ's superoperator for the filtered signal to be single-frequency.

    depths : list of ints
        The deterministic germ repetitions.  Must contain 0 (the phase
        reference that cancels the depth-independent SPAM/projector-tilt
        phase), must start at 1, and may at most double from one depth to the
        next (the RPE window-selection requirement).

    prep_fiducial, meas_fiducial : Circuit, optional
        Fiducial circuits applied before/after the germ powers.  Unlike RPE,
        these need NOT prepare a two-eigenstate superposition: any prep/meas
        pair with nonzero overlap on the targeted coherences works, and one
        generic pair serves every irrep at once.

    num_projection_rounds : int, optional
        The number of quadrature projection rounds (`k0`).  The number of
        circuits per depth is `k0 * (group_order - 1) + 1`.

    qubit_labels : tuple, optional
        The qubits this experiment design applies to.

    seed : int, optional
        Unused (all circuits are deterministic in 'exact' mode); accepted for
        interface compatibility.

    descriptor : str, optional
        A description of the experiment design.
    """

    def __init__(self, germ, group_order, irrep_indices, depths,
                 prep_fiducial=None, meas_fiducial=None, num_projection_rounds=2,
                 qubit_labels=None, seed=None,
                 descriptor='A character phase estimation experiment'):
        depths = [int(k) for k in depths]
        if 0 not in depths:
            raise ValueError("CPE depths must include 0 (the phase reference)")
        nonzero = sorted(k for k in depths if k > 0)
        if not nonzero or nonzero[0] != 1:
            raise ValueError("CPE depths must include 1 (the first RPE generation)")
        for prev, nxt in zip(nonzero[:-1], nonzero[1:]):
            if nxt > 2 * prev:
                raise ValueError("CPE depths may at most double between generations "
                                 "(%d -> %d violates the RPE window-selection requirement)"
                                 % (prev, nxt))
        irrep_indices = tuple(int(j) for j in irrep_indices)
        if len(irrep_indices) == 0:
            raise ValueError("irrep_indices must be non-empty")
        for j in irrep_indices:
            if not (0 < j < group_order):
                raise ValueError("CPE irrep indices must be nontrivial: in (0, group_order)")

        super().__init__(germ, group_order, irrep_indices[0], depths,
                         circuits_per_depth=0,  # 'exact' mode overrides this
                         prep_fiducial=prep_fiducial, meas_fiducial=meas_fiducial,
                         mode='exact', num_projection_rounds=num_projection_rounds,
                         qubit_labels=qubit_labels, seed=seed, descriptor=descriptor)
        self.irrep_indices = irrep_indices

    def character_weights_for(self, irrep_index):
        """
        The character (and quadrature) weight of each circuit for one irrep.

        Identical to :meth:`~pygsti.protocols.cgst.CharacterGSTGermDesign.character_weights`
        but for an arbitrary irrep index, enabling one design's circuits to be
        reweighted per targeted irrep.

        Parameters
        ----------
        irrep_index : int
            The irrep of `Z_group_order` to weight for.

        Returns
        -------
        list of numpy.ndarray
            One complex array per depth, in the same order as `circuit_lists`.
        """
        weights = [_ct.character_weights(self.group_order, irrep_index,
                                         [t % self.group_order for t in totals])
                   for totals in self.total_germ_powers()]
        quad = _ct.uniform_power_distribution(self.group_order, self.num_projection_rounds)
        return [w * quad * len(quad) for w in weights]


def create_2q_izz_unitary(theta_iz, theta_zi, theta_zz):
    """
    The diagonal two-qubit unitary `exp(-i/2 (theta_iz*IZ + theta_zi*ZI + theta_zz*ZZ))`.

    Parameters
    ----------
    theta_iz, theta_zi, theta_zz : float
        The rotation angles (radians) of the three commuting Pauli generators.

    Returns
    -------
    numpy.ndarray
        A 4x4 complex diagonal unitary, in the computational basis ordered
        `|00>, |01>, |10>, |11>` (first qubit = leftmost label).
    """
    phases = []
    for s1 in (1, -1):  # Z eigenvalue of qubit 0: |0> -> +1
        for s2 in (1, -1):
            phases.append(-0.5 * (theta_iz * s2 + theta_zi * s1 + theta_zz * s1 * s2))
    return _np.diag(_np.exp(1j * _np.array(phases)))


def izz_coherence_irreps(ks, order):
    """
    The irreps carrying the three product-state-accessible coherences of an IZ/ZI/ZZ germ.

    For the germ `exp(-i pi/order (k1*IZ + k2*ZI + k3*ZZ))` (see
    :func:`create_2q_diagonal_cpe_design`), the coherences between the
    computational-basis pairs `(01,00)`, `(10,00)` and `(11,10)` live in the
    `Z_order` irreps returned here, and their eigenphase deviations are
    `d_iz + d_zz`, `d_zi + d_zz` and `d_iz - d_zz` respectively, where `d_*`
    are the deviations of the germ's three generator angles from ideal.

    Parameters
    ----------
    ks : tuple of 3 ints
        The integer angle numerators `(k1, k2, k3)`.

    order : int
        The cyclic group order.

    Returns
    -------
    tuple of 3 ints
    """
    k1, k2, k3 = ks
    return ((k1 + k3) % order, (k2 + k3) % order, (k1 - k3) % order)


def make_2q_diagonal_model(ks=(1, 3, 4), order=13, deviations=(0., 0., 0.), depol=0.0,
                           qubit_labels=('Q0', 'Q1')):
    """
    An explicit 2Q model with a diagonal germ gate `Gd` and local sqrt(Y) gates.

    The ideal `Gd` is `exp(-i pi/order (k1*IZ + k2*ZI + k3*ZZ))`, i.e. the
    generator angles (in the `exp(-i/2 theta P)` convention) are
    `theta = 2*pi*k/order`; its Pauli-transfer matrix generates `Z_order`.  The noisy `Gd` adds the given generator-angle
    `deviations` (which commute with the ideal gate, so the model's germ
    eigenvalue deviations are known exactly) and a uniform depolarizing factor
    multiplying every non-identity Pauli eigenvalue by `1 - depol`.

    Parameters
    ----------
    ks : tuple of 3 ints, optional
        Integer angle numerators `(k1, k2, k3)`.  The default `(1, 3, 4)` mod
        13 makes the four eigenphases a perfect difference set: all twelve
        coherences of the germ's superoperator occupy distinct irreps.

    order : int, optional
        The cyclic group order of the ideal germ's superoperator.

    deviations : tuple of 3 floats, optional
        Angle errors (radians) added to the three generator angles.

    depol : float, optional
        Uniform depolarizing parameter: each non-identity Pauli eigenvalue of
        the noisy `Gd` is multiplied by `1 - depol`.

    qubit_labels : tuple, optional
        The two qubit labels.

    Returns
    -------
    ExplicitOpModel
    """
    from pygsti.models.modelconstruction import create_explicit_model as _create_explicit_model
    from pygsti.processors import QubitProcessorSpec as _QubitProcessorSpec

    thetas = tuple(2 * _np.pi * k / order for k in ks)
    u_ideal = create_2q_izz_unitary(*thetas)
    pspec = _QubitProcessorSpec(2, ['Gd', 'Gypi2', 'Gympi2'],
                                nonstd_gate_unitaries={'Gd': u_ideal},
                                availability={'Gd': [tuple(qubit_labels)]},
                                qubit_labels=list(qubit_labels))
    mdl = _create_explicit_model(pspec, ideal_gate_type='full')

    u_noisy = create_2q_izz_unitary(*(t + d for t, d in zip(thetas, deviations)))
    ptm = _unitary_to_pauligate(u_noisy)
    depol_ptm = _np.diag([1.0] + [1.0 - depol] * 15)
    mdl.operations[('Gd',) + tuple(qubit_labels)] = depol_ptm @ ptm
    return mdl


def create_2q_diagonal_cpe_design(depths=(0, 1, 2, 4, 8, 16, 32, 64),
                                  num_projection_rounds=2, ks=(1, 3, 4), order=13,
                                  qubit_labels=('Q0', 'Q1'), seed=None):
    """
    The CPE experiment design for the diagonal 2Q germ of :func:`make_2q_diagonal_model`.

    A single generic product prep/meas pair -- `|++>` prepared by
    `Gypi2:Gypi2` and unprepared by `Gympi2:Gympi2` -- excites ALL twelve
    coherences of the germ equally (amplitude 1/16 each): the multi-frequency
    nightmare for naive RPE, and exactly the situation character filtering
    resolves in post-processing.  The design targets the three irreps of
    :func:`izz_coherence_irreps`, from which all three generator-angle
    deviations are recovered (see :func:`extract_izz_phase_deviations`).

    Parameters
    ----------
    depths : list of ints, optional
        The RPE depth schedule (must include 0 and 1 and at most double).

    num_projection_rounds : int, optional
        The number of quadrature projection rounds (`k0`).

    ks : tuple of 3 ints, optional
        Integer angle numerators of the germ (see :func:`make_2q_diagonal_model`).

    order : int, optional
        The cyclic group order.

    qubit_labels : tuple, optional
        The two qubit labels.

    seed : int, optional
        Unused ('exact' mode is deterministic); accepted for interface
        compatibility.

    Returns
    -------
    CharacterPhaseEstimationDesign
    """
    q0, q1 = qubit_labels
    lbls = tuple(qubit_labels)
    germ = _Circuit([('Gd', q0, q1)], line_labels=lbls)
    prep_fid = _Circuit([('Gypi2', q0), ('Gypi2', q1)], line_labels=lbls)
    meas_fid = _Circuit([('Gympi2', q0), ('Gympi2', q1)], line_labels=lbls)
    return CharacterPhaseEstimationDesign(
        germ, order, izz_coherence_irreps(ks, order), depths,
        prep_fiducial=prep_fid, meas_fiducial=meas_fid,
        num_projection_rounds=num_projection_rounds, qubit_labels=lbls, seed=seed,
        descriptor="CPE experiment for the diagonal 2Q germ with (k1,k2,k3)=%s mod %d"
                   % (str(tuple(ks)), order))


def _success_fractions(design, dataset):
    """Per-depth lists of (success fraction, total counts) for `design`'s circuits."""
    fractions, totals = [], []
    for circuits, idealouts in zip(design.circuit_lists, design.idealout_lists):
        row_f, row_t = [], []
        for c, out in zip(circuits, idealouts):
            row = dataset[c]
            row_f.append(row.counts.get((out,), 0.0) / row.total)
            row_t.append(row.total)
        fractions.append(_np.array(row_f))
        totals.append(_np.array(row_t))
    return fractions, totals


def _unwound_phase(design, weights_per_depth, fractions):
    """
    Character-filter `fractions`, form RPE raw angles, and unwind.

    Returns `(signal, raw_angles, generation_estimates, phase_estimate)`;
    the phase estimate is wrapped to (-pi, pi].
    """
    signal = _np.array([_np.mean(w * f) for w, f in zip(weights_per_depth, fractions)])
    ref_idx = design.depths.index(0)
    z0 = signal[ref_idx]
    raw_angles = _collections.OrderedDict()
    for k, z in zip(design.depths, signal):
        if k == 0:
            continue
        raw_angles[k] = float(_np.angle(z * _np.conj(z0)) % (2 * _np.pi))
    rpe = _RPEAnalysis(_argparse.Namespace(raw_angles=raw_angles))
    estimates = [float(a) for a in rpe.angle_estimates]
    final = float((estimates[-1] + _np.pi) % (2 * _np.pi) - _np.pi)
    return signal, raw_angles, estimates, final


class CharacterPhaseEstimationResults(_proto.ProtocolResults):
    """
    The results of running :class:`CharacterPhaseEstimation`.

    Attributes of note: `irrep_indices`, `phase_estimates` (per-irrep
    eigenphase deviations, radians, in (-pi, pi]), `phase_stderrs` (bootstrap
    standard errors, or None), `generation_estimates` (per-irrep list of the
    RPE estimate after each generation), `raw_angles` and `signal(irrep)`.

    Parameters
    ----------
    data : ProtocolData
        The experimental data these results are generated from.

    protocol_instance : Protocol
        The protocol that generated these results.

    signals, raw_angles, generation_estimates, phase_estimates, phase_stderrs : dict
        Per-irrep analysis outputs (see :class:`CharacterPhaseEstimation`).
    """

    def __init__(self, data, protocol_instance, signals, raw_angles,
                 generation_estimates, phase_estimates, phase_stderrs):
        super().__init__(data, protocol_instance)
        design = data.edesign
        self.depths = list(design.depths)
        self.group_order = design.group_order
        self.irrep_indices = list(design.irrep_indices)
        self.signals_real = {str(j): [float(v) for v in _np.real(s)] for j, s in signals.items()}
        self.signals_imag = {str(j): [float(v) for v in _np.imag(s)] for j, s in signals.items()}
        self.raw_angles = _to_json_safe({str(j): dict(a) for j, a in raw_angles.items()})
        self.generation_estimates = _to_json_safe({str(j): g for j, g in generation_estimates.items()})
        self.phase_estimates = _to_json_safe({str(j): p for j, p in phase_estimates.items()})
        self.phase_stderrs = _to_json_safe({str(j): s for j, s in phase_stderrs.items()}) \
            if phase_stderrs else None

    def signal(self, irrep_index):
        """The complex character-filtered signal `z_j(k)` for one irrep (numpy.ndarray)."""
        key = str(irrep_index)
        return _np.array(self.signals_real[key]) + 1j * _np.array(self.signals_imag[key])

    def phases_by_irrep(self):
        """
        The per-irrep phase estimates (and stderrs) keyed by integer irrep index.

        Returns
        -------
        dict
            Maps irrep index to `(phase_estimate, phase_stderr_or_None)`.
        """
        return {int(j): (self.phase_estimates[j],
                         None if self.phase_stderrs is None else self.phase_stderrs[j])
                for j in self.phase_estimates}

    def plot(self, ax=None, true_phases=None):
        """
        Plot each irrep's RPE estimate versus generation depth.

        The `pi / (2*depth)` RPE error envelope is shaded around each final
        estimate; optional true phases are drawn as horizontal lines.

        Parameters
        ----------
        ax : matplotlib.axes.Axes, optional
            An axis to plot on (a new figure is created if None).

        true_phases : dict, optional
            Maps irrep index to the true eigenphase deviation.

        Returns
        -------
        matplotlib.axes.Axes
        """
        try:
            import matplotlib.pyplot as _plt
        except ImportError:
            raise ValueError("This function requires you to install matplotlib!")
        if ax is None:
            _, ax = _plt.subplots(figsize=(5, 3.5))
        gen_depths = [k for k in self.depths if k > 0]
        for j in self.irrep_indices:
            ests = _np.array(self.generation_estimates[str(j)])
            ests = (ests + _np.pi) % (2 * _np.pi) - _np.pi
            line, = ax.plot(gen_depths, ests, 'o-', label='irrep %d' % j)
            if true_phases and j in true_phases:
                ax.axhline(true_phases[j], color=line.get_color(), ls=':', alpha=0.7)
        envelope = _np.pi / (2 * _np.array(gen_depths, dtype=float))
        ax.plot(gen_depths, envelope, 'k--', alpha=0.3, label=r'$\pm\pi/2k$ envelope')
        ax.plot(gen_depths, -envelope, 'k--', alpha=0.3)
        ax.set_xscale('log', base=2)
        ax.set_xlabel('germ depth $k$')
        ax.set_ylabel('estimated phase deviation (rad)')
        ax.legend(loc='best', fontsize=8)
        return ax


class CharacterPhaseEstimation(_proto.Protocol):
    """
    The character phase estimation analysis protocol.

    For each targeted irrep, character-filters the data into a complex signal
    `z_j(k)`, forms the RPE raw angles `arg(z_j(k) * conj(z_j(0)))` -- the
    depth-0 reference cancels the k-independent SPAM/projector-tilt phase --
    and unwinds them with the standard RPE per-generation window selection.
    Uncertainties come from a multinomial bootstrap of the per-circuit counts,
    rerunning the full filter-and-unwind pipeline on each resample.

    Note this deliberately does NOT reuse the exponential+phase fit of
    :func:`pygsti.algorithms.cgstfit.fit_complex_decay`: its `numpy.unwrap`
    phase seeding assumes closely spaced depths and aliases on the geometric
    schedules CPE uses.

    Parameters
    ----------
    bootstrap_samples : int, optional
        The number of multinomial bootstrap resamples for error bars
        (0 disables bootstrapping).

    seed : int, optional
        Seed for the bootstrap resampling.

    name : str, optional
        The name of this protocol.
    """

    def __init__(self, bootstrap_samples=200, seed=None, name=None):
        super().__init__(name)
        self.bootstrap_samples = bootstrap_samples
        self.seed = seed

    def run(self, data, memlimit=None, comm=None):
        """
        Run this protocol on `data`.

        Parameters
        ----------
        data : ProtocolData
            The input data.  Its experiment design must be a
            :class:`CharacterPhaseEstimationDesign`.

        memlimit : int, optional
            A rough per-processor memory limit in bytes (unused).

        comm : mpi4py.MPI.Comm, optional
            An MPI communicator (unused).

        Returns
        -------
        CharacterPhaseEstimationResults
        """
        design = data.edesign
        assert isinstance(design, CharacterPhaseEstimationDesign), \
            "This protocol can only be run on a CharacterPhaseEstimationDesign"
        fractions, totals = _success_fractions(design, data.dataset)
        weights = {j: design.character_weights_for(j) for j in design.irrep_indices}

        signals, raw_angles, generations, estimates = {}, {}, {}, {}
        for j in design.irrep_indices:
            signals[j], raw_angles[j], generations[j], estimates[j] = \
                _unwound_phase(design, weights[j], fractions)

        stderrs = None
        if self.bootstrap_samples > 0:
            rand_state = _np.random.RandomState(self.seed)
            resampled = {j: [] for j in design.irrep_indices}
            for _ in range(self.bootstrap_samples):
                boot = [rand_state.binomial(t.astype(int), _np.clip(f, 0.0, 1.0)) / t
                        for f, t in zip(fractions, totals)]
                for j in design.irrep_indices:
                    _, _, _, est = _unwound_phase(design, weights[j], boot)
                    resampled[j].append(est)
            # circular std: bootstrap phases can straddle the +-pi wrap point
            stderrs = {}
            for j, ests in resampled.items():
                ests = _np.array(ests)
                center = _np.angle(_np.mean(_np.exp(1j * ests)))
                stderrs[j] = float(_np.std((ests - center + _np.pi) % (2 * _np.pi) - _np.pi))

        return CharacterPhaseEstimationResults(data, self, signals, raw_angles,
                                               generations, estimates, stderrs)


def extract_izz_phase_deviations(phases_by_irrep, ks=(1, 3, 4), order=13):
    """
    Invert CPE eigenphase deviations into IZ/ZI/ZZ generator-angle deviations.

    For the diagonal 2Q germ of :func:`make_2q_diagonal_model`, the three
    coherence irreps `(ja, jb, jc)` of :func:`izz_coherence_irreps` have
    eigenphase deviations `delta_a = d_iz + d_zz`, `delta_b = d_zi + d_zz`,
    `delta_c = d_iz - d_zz`, so

        d_iz = (delta_a + delta_c) / 2
        d_zz = (delta_a - delta_c) / 2
        d_zi = delta_b - d_zz

    Parameters
    ----------
    phases_by_irrep : dict
        Maps irrep index to either a phase estimate (float) or a tuple
        `(phase_estimate, stderr_or_None)`, e.g. the output of
        :meth:`CharacterPhaseEstimationResults.phases_by_irrep`.

    ks : tuple of 3 ints, optional
        The germ's integer angle numerators.

    order : int, optional
        The cyclic group order.

    Returns
    -------
    dict
        Keys `'d_iz'`, `'d_zi'`, `'d_zz'` (the generator-angle deviations,
        radians), matching `'*_stderr'` entries when input stderrs were given,
        and `'theta_iz'`, `'theta_zi'`, `'theta_zz'` (the absolute generator
        angles, ideal `2*pi*k/order` plus deviation).
    """
    ja, jb, jc = izz_coherence_irreps(ks, order)

    def value_and_err(j):
        v = phases_by_irrep[j]
        return (float(v[0]), v[1]) if isinstance(v, (tuple, list)) else (float(v), None)

    (da, ea), (db, eb), (dc, ec) = value_and_err(ja), value_and_err(jb), value_and_err(jc)
    out = {'d_iz': (da + dc) / 2.0, 'd_zz': (da - dc) / 2.0}
    out['d_zi'] = db - out['d_zz']
    if all(e is not None for e in (ea, eb, ec)):
        out['d_iz_stderr'] = _np.sqrt(ea ** 2 + ec ** 2) / 2.0
        out['d_zz_stderr'] = _np.sqrt(ea ** 2 + ec ** 2) / 2.0
        out['d_zi_stderr'] = _np.sqrt(eb ** 2 + (ea ** 2 + ec ** 2) / 4.0)
    for name, k, dev in [('theta_iz', ks[0], out['d_iz']),
                         ('theta_zi', ks[1], out['d_zi']),
                         ('theta_zz', ks[2], out['d_zz'])]:
        out[name] = 2 * _np.pi * k / order + dev
    return out
