"""Exact connected-cluster malignant-set enumeration: m(v).

Counts *minimal malignant clusters* of weight ``v``: connected (in the
shared-detector graph) sets of ``v`` error mechanisms that cause a logical
failure, with no proper nonempty subset that also fails. These are the
"cores" of the failure spectrum -- the exact, tightest-possible anchors for
the failure-spectrum onset (``failure_spectrum.py``) and a connectivity-aware
refinement of the brute-force weight enumeration in ``malignant.py`` (which
enumerates *all* ``C(n, w)`` combinations, not just connected ones, and does
not distinguish minimal from non-minimal malignant sets).

Connectivity graph
-------------------
Vertices are mechanism indices; an edge (i, j) exists iff the two mechanisms
share at least one detector target (``splitting_swap.build_detector_adjacency``).
Mechanisms that touch no detector are isolated vertices -- they still count as
size-1 clusters if the single mechanism alone causes a failure.

Minimality is checked by brute force over all ``2**v - 2`` proper nonempty
subsets of a candidate weight-``v`` set. Checking only the ``v - 1`` subsets
obtained by removing one element at a time is NOT sound: whether a fault set
causes a logical decoder failure is not monotone in set inclusion (adding or
removing a single mechanism can flip the decoder's prediction either way), so
a smaller malignant subset need not be reachable by single-element removal
from a larger malignant superset containing it.

Why there is no cheap pre-oracle filter
-----------------------------------------
A tempting shortcut: skip the oracle call for a candidate set ``S`` if no
mechanism in ``S`` touches a logical observable (``mech.observables`` empty
for every member), on the theory that ``S`` cannot possibly flip the decoded
observable. This is unsound. The decoder only ever sees the syndrome, not
which specific mechanisms fired; a syndrome-preserving replacement of ``S``
by an alternate (non-active) explanation can shift the decoder's prediction
even when ``S`` itself never touches an observable directly -- the decoder's
*correction*, not ``S``, is what may flip the reported observable. So every
candidate set must be passed to the oracle. Safe prunings do exist in
principle (bounding the geometric reach of a cluster before it could possibly
reach a boundary/observable, or bounds derived from the decoder's suboptimality
gap) but are not implemented here; they are noted as future work.

Enumeration algorithm
----------------------
Connected induced subgraphs of size <= K are enumerated by the standard
duplicate-free scheme (each connected set is generated by, and only by, the
recursive expansion rooted at its minimum-index vertex; see e.g. Wernicke's
ESU algorithm for enumerating connected subgraphs). Recursion depth is
bounded by K (small); breadth is bounded by a ``max_nodes`` visited-set
budget so pathological (dense) graphs fail soft (a partial, flagged result)
rather than never terminating.
"""

from __future__ import annotations

import dataclasses
import itertools
import math
from collections.abc import Iterator, Sequence
from typing import Any

import numpy as np

from .failure_spectrum import poisson_binomial_pmf
from .interfaces import ErrorModel, Estimator, ForwardSimulator
from .rare_event import MechanismCatalog
from .splitting_swap import build_detector_adjacency
from .weight_points import WeightPoint

#: Default visited-node budget for the connected-subgraph search. Chosen to
#: keep d=5 / max_weight=3 (thousands of mechanisms, weight-3 clusters)
#: comfortably feasible while still catching runaway enumerations on denser
#: graphs.
DEFAULT_MAX_NODES = 200_000_000


@dataclasses.dataclass
class _EnumState:
    """Mutable node-budget bookkeeping shared across the whole recursive search."""

    nodes_visited: int = 0
    budget_exceeded: bool = False


def _iter_connected_sets(
    neighbors: Sequence[tuple[int, ...]],
    n: int,
    max_weight: int,
    max_nodes: int,
    state: _EnumState,
) -> Iterator[tuple[int, ...]]:
    """Yield each connected induced subgraph of size 1..max_weight exactly once.

    Implements the duplicate-free recursion: for each root ``r`` (the set's
    minimum element), extensions are restricted to neighbors with index > r,
    and each candidate extension vertex is only ever *offered* once per root
    (tracked via ``visited``), which is what guarantees no connected set is
    generated twice.
    """

    def rec(root: int, s: tuple[int, ...], ext: list[int], visited: set[int]) -> Iterator[tuple[int, ...]]:
        if state.budget_exceeded:
            return
        state.nodes_visited += 1
        if state.nodes_visited > max_nodes:
            state.budget_exceeded = True
            return
        # `s` is built up in traversal order (only its first element, the
        # root, is guaranteed to be the minimum); sort before handing it to
        # callers, who treat each connected set as an unordered vertex set.
        yield tuple(sorted(s))
        if len(s) == max_weight:
            return
        for idx in range(len(ext)):
            if state.budget_exceeded:
                return
            v = ext[idx]
            new_neighbors = [u for u in neighbors[v] if u > root and u not in visited]
            new_visited = visited | set(new_neighbors)
            yield from rec(root, s + (v,), ext[idx + 1 :] + new_neighbors, new_visited)

    for r in range(n):
        if state.budget_exceeded:
            return
        ext = [u for u in neighbors[r] if u > r]
        visited = set(ext)
        visited.add(r)
        yield from rec(r, (r,), ext, visited)


def enumerate_connected_subgraphs(
    neighbors: Sequence[tuple[int, ...]],
    n: int,
    max_weight: int,
    max_nodes: int = DEFAULT_MAX_NODES,
) -> tuple[dict[int, list[tuple[int, ...]]], int, bool]:
    """Enumerate all connected induced subgraphs of size 1..max_weight.

    Pure graph enumeration with no oracle involved; used both as the engine
    behind ``enumerate_connected_malignant`` and as a directly testable unit
    (compare against brute-force ``itertools.combinations`` + connectivity
    check on small graphs).

    Returns ``(sets_by_size, nodes_visited, completed)`` where
    ``sets_by_size[v]`` lists every connected set of size ``v`` visited (each
    exactly once, as a sorted tuple), ``nodes_visited`` counts recursion
    visits, and ``completed`` is False if ``max_nodes`` was exceeded before
    the search finished (in which case ``sets_by_size`` is a partial result).
    """
    if max_weight < 1:
        raise ValueError(f"max_weight must be at least 1; got {max_weight}.")
    if len(neighbors) != n:
        raise ValueError(f"neighbors has {len(neighbors)} entries but n={n}.")

    state = _EnumState()
    sets_by_size: dict[int, list[tuple[int, ...]]] = {v: [] for v in range(1, max_weight + 1)}
    for s in _iter_connected_sets(neighbors, n, max_weight, max_nodes, state):
        sets_by_size[len(s)].append(s)
    return sets_by_size, state.nodes_visited, not state.budget_exceeded


@dataclasses.dataclass
class ConnectedEnumerationResult:
    """Result of exact connected-cluster malignant-set enumeration.

    Attributes:
        max_weight: Largest cluster weight ``v`` explored.
        minimal_counts: ``m(v)`` for ``v`` in ``1..max_weight``: the number of
            minimal malignant connected sets of size ``v``.
        non_minimal_counts: Number of connected malignant sets of size ``v``
            that are NOT minimal (malignant but contain a smaller failing
            subset).
        minimal_sets: The minimal malignant sets themselves, as sorted tuples
            of mechanism indices, keyed by weight ``v``. These are the "cores"
            other methods (e.g. the failure-spectrum onset) can consume.
        nodes_visited: Total connected-subgraph search-tree nodes visited.
        oracle_calls: Total ``simulator.fails`` calls made (malignancy checks
            plus minimality subset checks).
        completed: False if the ``max_nodes`` search budget was exceeded
            before the enumeration finished; in that case all counts and
            ``minimal_sets`` are partial (undercounts -- a genuine minimal
            malignant set may lie outside the explored fraction of the search
            tree, but nothing counted is a false positive).
    """

    max_weight: int
    minimal_counts: dict[int, int]
    non_minimal_counts: dict[int, int]
    minimal_sets: dict[int, list[tuple[int, ...]]]
    nodes_visited: int
    oracle_calls: int
    completed: bool


def enumerate_connected_malignant(
    catalog: MechanismCatalog,
    oracle: ForwardSimulator,
    *,
    max_weight: int,
    max_nodes: int = DEFAULT_MAX_NODES,
    verbose: bool = False,
) -> ConnectedEnumerationResult:
    """Exactly enumerate minimal malignant connected clusters up to ``max_weight``.

    For every connected induced subgraph ``S`` of the shared-detector graph
    (size 1..max_weight), calls ``oracle.fails(S)``; if ``S`` is malignant,
    exhaustively checks all ``2**|S| - 2`` proper nonempty subsets to decide
    minimality (see module docstring for why this cannot be shortcut to
    single-element removals, and why there is no cheap pre-oracle filter).
    """
    if max_weight < 1:
        raise ValueError(f"max_weight must be at least 1; got {max_weight}.")

    n = len(catalog.mechanisms)
    neighbors = build_detector_adjacency(catalog)

    state = _EnumState()
    oracle_calls = 0
    minimal_counts: dict[int, int] = dict.fromkeys(range(1, max_weight + 1), 0)
    non_minimal_counts: dict[int, int] = dict.fromkeys(range(1, max_weight + 1), 0)
    minimal_sets: dict[int, list[tuple[int, ...]]] = {v: [] for v in range(1, max_weight + 1)}

    for s in _iter_connected_sets(neighbors, n, max_weight, max_nodes, state):
        v = len(s)
        oracle_calls += 1
        if not oracle.fails(set(s)):
            continue

        minimal = True
        for k in range(1, v):
            for sub in itertools.combinations(s, k):
                oracle_calls += 1
                if oracle.fails(set(sub)):
                    minimal = False
                    break
            if not minimal:
                break

        if minimal:
            minimal_counts[v] += 1
            minimal_sets[v].append(s)
        else:
            non_minimal_counts[v] += 1

        if verbose and oracle_calls % 100_000 == 0:
            print(
                f"connected_enumeration: nodes_visited={state.nodes_visited} oracle_calls={oracle_calls} "
                f"minimal_counts={minimal_counts}"
            )

    return ConnectedEnumerationResult(
        max_weight=max_weight,
        minimal_counts=minimal_counts,
        non_minimal_counts=non_minimal_counts,
        minimal_sets=minimal_sets,
        nodes_visited=state.nodes_visited,
        oracle_calls=oracle_calls,
        completed=not state.budget_exceeded,
    )


def weight_points(result: ConnectedEnumerationResult) -> list[WeightPoint]:
    """Convert a ``ConnectedEnumerationResult`` into the shared ``WeightPoint`` contract.

    Each point has ``method="connected_enumeration"``, ``kind="m_v"``,
    ``estimate=m(v)``, and ``rel_err=0.0`` (an exact count). When the search
    completed within budget the count is exact (``exact=True``); when the
    node budget was exceeded, the count is a certified lower bound on the
    true m(v) (``lower_bound=True``, ``exact=False``) since the search only
    ever counts genuine minimal malignant sets, never overcounts.
    """
    points = []
    for v in sorted(result.minimal_counts):
        meta: dict[str, Any] = {
            "non_minimal_count": result.non_minimal_counts[v],
            "nodes_visited": result.nodes_visited,
            "oracle_calls": result.oracle_calls,
            "completed": result.completed,
        }
        points.append(
            WeightPoint(
                method="connected_enumeration",
                kind="m_v",
                weight=v,
                estimate=float(result.minimal_counts[v]),
                rel_err=0.0,
                exact=result.completed,
                lower_bound=not result.completed,
                meta=meta,
            )
        )
    return points


class ConnectedEnumerationEstimator(Estimator):
    """``Estimator``-protocol wrapper around ``enumerate_connected_malignant``.

    Ignores ``error_model`` (the enumeration is a property of the connectivity
    graph and the oracle alone, not of any particular physical rate) but
    accepts it to satisfy the ``Estimator`` protocol signature.
    """

    def estimate(
        self,
        error_model: ErrorModel,
        simulator: ForwardSimulator,
        **kwargs: Any,
    ) -> dict[str, Any]:
        if "catalog" not in kwargs:
            raise ValueError("catalog must be provided to ConnectedEnumerationEstimator")
        if "max_weight" not in kwargs:
            raise ValueError("max_weight must be provided to ConnectedEnumerationEstimator")

        catalog = kwargs["catalog"]
        result = enumerate_connected_malignant(
            catalog,
            simulator,
            max_weight=kwargs["max_weight"],
            max_nodes=kwargs.get("max_nodes", DEFAULT_MAX_NODES),
            verbose=kwargs.get("verbose", False),
        )
        return {
            "result": result,
            "weight_points": weight_points(result),
            "minimal_malignant_sets": result.minimal_sets,
        }


def predicted_f_w(m_counts: dict[int, int], n: int, w: int) -> float:
    """First-order onset prediction of the failure spectrum from cluster counts.

    Uniform-probability approximation:

        f(w) ~= sum_v m(v) * C(n - v, w - v) / C(n, w)

    i.e. the probability that a uniformly random weight-``w`` fault set
    contains at least... more precisely, a first-order (union-bound-style)
    estimate of the chance a weight-w set contains one of the m(v) known
    minimal malignant clusters of size v <= w, treating clusters as though
    they never co-occur in the same weight-w set (valid near onset, where
    weight-w sets containing two disjoint size->=1 clusters are rare).

    This ignores the heterogeneity of mechanism probabilities entirely (every
    weight-w fault set is treated as equally likely); see
    ``predicted_f_w_weighted`` for the probability-weighted generalization
    that also handles heterogeneous q_i(p), at the same over-counting caveat.
    """
    if n < 0:
        raise ValueError(f"n must be nonnegative; got {n}.")
    if w < 0:
        raise ValueError(f"w must be nonnegative; got {w}.")
    denom = math.comb(n, w)
    if denom == 0:
        return 0.0
    numer = 0.0
    for v, m_v in m_counts.items():
        if v > w or m_v <= 0:
            continue
        numer += m_v * math.comb(n - v, w - v)
    return numer / denom


def predicted_f_w_weighted(
    minimal_sets: Sequence[tuple[int, ...]],
    probs: np.ndarray,
    w: int,
) -> float:
    """Heterogeneous-probability onset prediction of f(w) from minimal clusters.

    For each minimal malignant cluster ``c``,

        P(all of c active) * P(exactly w - |c| of the OTHER mechanisms active)

    is the probability that a weight-``w`` fault set is exactly ``c`` plus
    ``w - |c|`` further (non-``c``) active mechanisms -- i.e. that the fault
    set "contains" cluster ``c``. Summing over clusters and dividing by
    ``Pr[W = w]`` (from ``failure_spectrum.poisson_binomial_pmf``) gives a
    first-order estimate of f(w) = P(fail | W = w): a weight-w set containing
    any minimal malignant cluster is presumed to fail (true, since decoder
    failure only requires *some* subset to be malignant), so this
    over-COUNTS weight-w sets that contain two (or more) distinct minimal
    clusters simultaneously -- each is counted once per cluster it contains.
    This is negligible near the onset weight (where clusters are sparse and
    disjoint double-containment is rare) but increasingly overestimates f(w)
    as w grows past onset.
    """
    if w < 0:
        raise ValueError(f"w must be nonnegative; got {w}.")
    q = np.asarray(probs, dtype=np.float64)
    n = len(q)

    pmf_w = poisson_binomial_pmf(q, max_weight=w)
    if w >= len(pmf_w) or pmf_w[w] <= 0:
        return float("nan")
    p_w = float(pmf_w[w])

    total = 0.0
    for c in minimal_sets:
        v = len(c)
        if v > w:
            continue
        need = w - v
        p_cluster = float(np.prod(q[list(c)]))
        if p_cluster <= 0:
            continue
        complement_mask = np.ones(n, dtype=bool)
        complement_mask[list(c)] = False
        complement_pmf = poisson_binomial_pmf(q[complement_mask], max_weight=need)
        if need >= len(complement_pmf):
            continue
        total += p_cluster * float(complement_pmf[need])

    return total / p_w
