"""
Standard-gauge fixing for character gate set tomography (cGST)
"""
#***************************************************************************************************
# Copyright 2015, 2019, 2025 National Technology & Engineering Solutions of Sandia, LLC (NTESS).
# Under the terms of Contract DE-NA0003525 with NTESS, the U.S. Government retains certain rights
# in this software.
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.  You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0 or in the LICENSE file in the root pyGSTi directory.
#***************************************************************************************************

import warnings as _warnings

import numpy as _np
import scipy.linalg as _spl
import scipy.optimize as _spo

from pygsti.baseobjs.label import Label as _Label
from pygsti.modelmembers.operations.lindbladerrorgen import LindbladErrorgen as _LindbladErrorgen
from pygsti.models.gaugegroup import FullGaugeGroupElement as _FullGaugeGroupElement
from pygsti.tools import optools as _ot

# The cGST manuscript reports gate error parameters in a "standard gauge" that is
# built in two stages (manuscript Apps. "Construction of the commuting gauge" and
# "Construction of the standard gauge"):
#
#  1. A *reference gate* (the S gate for the {S, sqrt(Y)} gate set) is brought to the
#     "commuting gauge", in which its error channel commutes with the ideal gate.  This
#     is done exactly, by matching the eigenspaces of the noisy gate to those of the
#     ideal gate (`commuting_gauge_transform`).  What is left is the group of
#     trace-preserving (TP) gauge transformations that commute with the ideal reference
#     gate, generated by the Lie algebra returned by `tp_commutant_basis`.
#
#  2. The residual freedom is spent on the *other* gates: the summed Frobenius norm of
#     their errors (transformed channel minus ideal gate) is minimized over that group.
#     For {S, sqrt(Y)} these are the manuscript's transformations A_1 (equatorial scale
#     xi), A_2 (axis scale zeta and axis shift eta) and A_3 (equatorial rotation psi).
#     Including psi in the same least-squares problem places the sqrt(Y) axis tilt in
#     the Y-Z plane, i.e. the relational coherent error along X, which is exactly the
#     manuscript's convention (`standard_gauge_transform`).
#
# One subtlety is not spelled out in the manuscript.  Gauge directions that commute with
# *every* ideal gate (for an irreducible single-qubit gate set this is the uniform
# scaling of the Bloch ball, diag(0, 1, 1, 1)) do not move any gate at first order in
# the noise, so they are not fixed by the gate errors: they only rescale the affine
# (non-unital) parts of all gates, and the Frobenius objective decreases monotonically as
# the scale goes to zero.  These "SPAM-only" directions are therefore separated from the
# gate-fixed ones and fixed by a secondary criterion, namely that the model's SPAM be as
# close as possible to the target SPAM.  For the cGST pipeline, whose reconstructed
# models carry ideal SPAM, this leaves those directions essentially untouched while
# making the gauge fixing well posed and gauge invariant.


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _check_pp_basis(model):
    """Raise if `model` is not expressed in the normalized Pauli-product basis."""
    if model.basis.name != 'pp':
        raise ValueError("cGST gauge fixing assumes the normalized Pauli-product ('pp') basis, "
                         "but the model's basis is %s" % repr(model.basis.name))


def _resolve_gate_label(target_model, gate):
    """Resolve `gate` (a Label, tuple, or bare gate name) to a key of `target_model.operations`."""
    keys = list(target_model.operations.keys())
    if isinstance(gate, _Label):
        if gate in keys:
            return gate
    elif isinstance(gate, tuple):
        lbl = _Label(gate)
        if lbl in keys:
            return lbl
    elif isinstance(gate, str):
        if _Label(gate) in keys:
            return _Label(gate)
        matches = [k for k in keys if k.name == gate]
        if len(matches) == 1:
            return matches[0]
        if len(matches) > 1:
            raise ValueError("Gate name %s is ambiguous in the target model: %s" % (gate, matches))
    raise KeyError("Gate %s not found among the target model's operations %s" % (repr(gate), keys))


def _dense(op):
    return _np.asarray(op.to_dense(), dtype=float)


def _cluster_indices(values, tol):
    """
    Group the (complex) `values` into clusters of mutually close values.

    Returns a list of (representative value, list of indices), ordered by first appearance.
    """
    clusters = []
    for i, v in enumerate(values):
        for c in clusters:
            if abs(v - c[0]) <= tol:
                c[1].append(i)
                break
        else:
            clusters.append([v, [i]])
    return [(c[0], c[1]) for c in clusters]


def _spectral_projectors(mx, tol):
    """
    Eigen-decompose `mx` and return (cluster values, multiplicities, spectral projectors).

    The projectors P_c = V_c (V^{-1})_c project onto the (generalized) eigenspace of each
    cluster of eigenvalues along the others; they sum to the identity and P_c P_c' = 0.
    """
    evals, V = _np.linalg.eig(mx)
    cond = _np.linalg.cond(V)
    if not _np.isfinite(cond) or cond > 1e12:
        raise ValueError("Superoperator is not (numerically) diagonalizable: eigenvector matrix "
                         "condition number %g" % cond)
    Vinv = _np.linalg.inv(V)
    clusters = _cluster_indices(evals, tol)
    values = _np.array([c[0] for c in clusters])
    mults = [len(c[1]) for c in clusters]
    projs = [V[:, idx] @ Vinv[idx, :] for _, idx in clusters]
    return values, mults, projs, evals


def _commutator_map(G):
    """Matrix of K -> K G - G K acting on row-major vec(K)."""
    n = G.shape[0]
    return _np.kron(_np.identity(n), G.T) - _np.kron(G, _np.identity(n))


def _tp_row_constraints(n):
    """Rows selecting the first row of a row-major vectorized n x n matrix."""
    rows = _np.zeros((n, n * n))
    for j in range(n):
        rows[j, j] = 1.0
    return rows


def _orthonormal_complement(Q, m):
    """Orthonormal basis (columns) of the complement of span(Q) in R^m (Q may have 0 columns)."""
    if Q.shape[1] == 0:
        return _np.identity(m)
    return _spl.null_space(Q.T)


def _expm_combo(coeffs, mxs):
    n = mxs[0].shape[0] if len(mxs) > 0 else None
    if n is None or len(coeffs) == 0:
        return None
    K = _np.zeros((n, n))
    for c, M in zip(coeffs, mxs):
        K += c * M
    return _spl.expm(K)


def _least_squares(fun, x0, args=(), diff_step=None, jac='2-point'):
    """Wrapper choosing 'lm' when possible (needs #residuals >= #params)."""
    x0 = _np.asarray(x0, dtype=float)
    nres = fun(x0, *args).size
    method = 'lm' if nres >= x0.size else 'trf'
    return _spo.least_squares(fun, x0, args=args, method=method, jac=jac, xtol=1e-14, ftol=1e-14,
                              gtol=1e-14, max_nfev=2000, diff_step=diff_step)


# ---------------------------------------------------------------------------
# stage 1: the commuting gauge
# ---------------------------------------------------------------------------

def commuting_gauge_transform(noisy_superop, ideal_superop, tol=1e-6):
    """
    Gauge transformation bringing a noisy gate to the *commuting gauge* of its ideal counterpart.

    This is the exact construction of the cGST manuscript's appendix "Construction of
    the commuting gauge".  Writing the noisy gate `Lam` and the ideal gate `G` in
    eigen-decomposed form, each noisy eigenvalue is paired with the ideal eigenvalue
    cluster it is closest to, and the transformation `A = W V^{-1}` maps the noisy
    eigenvectors `V` onto (ideal-eigenspace) vectors `W`, so that `A Lam A^{-1}` is
    block diagonal with respect to the spectral projectors of `G` and hence commutes
    with `G` *exactly*.

    The eigenvector normalizations are fixed canonically by choosing `W_c = P_c V_c`,
    where `P_c` is the ideal spectral projector of cluster `c`.  Equivalently

        A = sum_c P_c Pi_c,

    where `Pi_c` is the noisy spectral projector of cluster `c`.  This choice is
    basis free, makes `A` real automatically (conjugate clusters contribute conjugate
    terms), tends to the identity as the noise vanishes, and is trace preserving:
    since `<<I|` is an exact left fixed point of any TP `Lam`, it lies in the noisy
    cluster around the ideal eigenvalue 1, so `<<I| A = <<I| Pi_1 = <<I|`.  Within
    the near-degenerate cluster {1, lambda_1} of, e.g., the S gate this automatically
    pairs the exact unit eigenvalue with the identity direction; the noisy fixed point
    is mapped to its projection onto the ideal eigenvalue-1 eigenspace, which is what
    produces the active-error entry of the manuscript's commuting form.

    Parameters
    ----------
    noisy_superop : numpy.ndarray
        The noisy gate's superoperator (real, TP, in a basis whose first element is
        proportional to the identity, e.g. 'pp').

    ideal_superop : numpy.ndarray
        The ideal gate's superoperator in the same basis (diagonalizable; for a
        unitary gate it is orthogonal).

    tol : float, optional
        Tolerance used to identify degenerate ideal eigenvalues and to check trace
        preservation of the inputs.

    Returns
    -------
    numpy.ndarray
        The real gauge matrix `A`, with `A[0, :] = e_0`, such that
        `A @ noisy_superop @ inv(A)` commutes with `ideal_superop`.

    Raises
    ------
    ValueError
        If the noisy spectrum cannot be unambiguously assigned to the ideal eigenvalue
        clusters (noise too large), or if the construction fails to be real.
    """
    Lam = _np.asarray(noisy_superop, dtype=float)
    G = _np.asarray(ideal_superop, dtype=float)
    n = G.shape[0]
    if G.shape != (n, n) or Lam.shape != (n, n):
        raise ValueError("Superoperators must be square matrices of the same dimension")
    e0 = _np.zeros(n); e0[0] = 1.0
    if _np.linalg.norm(G[0, :] - e0) > tol or _np.linalg.norm(Lam[0, :] - e0) > tol:
        raise ValueError("commuting_gauge_transform expects trace-preserving superoperators "
                         "(first row equal to e_0) in a basis whose first element is the identity")

    mu, ideal_mults, P, _ = _spectral_projectors(G, tol)
    if len(mu) > 1:
        gaps = [abs(mu[i] - mu[j]) for i in range(len(mu)) for j in range(i)]
        min_gap = min(gaps)
    else:
        min_gap = _np.inf

    evals, V = _np.linalg.eig(Lam)
    condV = _np.linalg.cond(V)
    if not _np.isfinite(condV) or condV > 1e12:
        raise ValueError("Noisy superoperator is not (numerically) diagonalizable "
                         "(eigenvector condition number %g)" % condV)
    Vinv = _np.linalg.inv(V)

    # assign each noisy eigenvalue to the nearest ideal cluster
    dists = _np.abs(evals[:, None] - mu[None, :])
    assignment = _np.argmin(dists, axis=1)
    nearest = dists[_np.arange(n), assignment]
    if _np.any(nearest >= 0.5 * min_gap):
        bad = [(evals[k], mu[assignment[k]]) for k in range(n) if nearest[k] >= 0.5 * min_gap]
        raise ValueError("Cannot separate the noisy spectrum into the ideal eigenvalue clusters "
                         "(noise too large): eigenvalue(s) %s are not within half the smallest "
                         "ideal gap %g of their nearest ideal eigenvalue" % (bad, min_gap))
    counts = _np.bincount(assignment, minlength=len(mu))
    if any(int(c) != m for c, m in zip(counts, ideal_mults)):
        raise ValueError("Noisy eigenvalue clusters do not match the ideal multiplicities: "
                         "ideal eigenvalues %s have multiplicities %s but %s noisy eigenvalues "
                         "were assigned to them" % (mu, ideal_mults, list(counts)))

    A = _np.zeros((n, n), dtype=complex)
    for c in range(len(mu)):
        idx = _np.where(assignment == c)[0]
        Pi_c = V[:, idx] @ Vinv[idx, :]
        A += P[c] @ Pi_c

    if _np.max(_np.abs(A.imag)) > 1e-8:
        raise ValueError("Commuting-gauge transformation failed to be real (max imaginary part %g)"
                         % _np.max(_np.abs(A.imag)))
    A = A.real.copy()
    if _np.linalg.norm(A[0, :] - e0) > 1e-8:
        raise ValueError("Commuting-gauge transformation failed to be trace preserving")
    A[0, :] = e0  # snap away roundoff so the transformed model is exactly TP
    condA = _np.linalg.cond(A)
    if not _np.isfinite(condA) or condA > 1e12:
        raise ValueError("Commuting-gauge transformation is singular (condition number %g)" % condA)
    return A


# ---------------------------------------------------------------------------
# residual freedom: the TP commutant
# ---------------------------------------------------------------------------

def tp_commutant_basis(ideal_superop, tol=1e-8):
    """
    Real orthonormal basis of TP-compatible generators commuting with an ideal gate.

    These are the matrices `K` with vanishing first row (so that `expm(K)` has first
    row `e_0`, i.e. is a trace-preserving gauge transformation) satisfying
    `K G = G K`.  They generate the residual gauge freedom left after the reference
    gate has been brought to its commuting gauge.

    For a single-qubit pi/2 rotation such as the S gate this space is four
    dimensional and corresponds to the manuscript's residual transformations: an
    equatorial scale (A_1, xi), an axis scale and an axis shift (A_2, zeta and eta),
    and an equatorial rotation (A_3, psi).  For a reference gate with a degenerate
    nontrivial eigenvalue (e.g. a pi rotation) the commutant, and hence this basis,
    is larger.

    Parameters
    ----------
    ideal_superop : numpy.ndarray
        The ideal gate's superoperator.

    tol : float, optional
        Relative singular-value cutoff used to determine the null space.

    Returns
    -------
    list of numpy.ndarray
        Matrices `K_i`, orthonormal with respect to the Frobenius inner product.  The
        particular basis within the commutant is arbitrary (it is whatever the SVD
        returns).
    """
    G = _np.asarray(ideal_superop, dtype=float)
    n = G.shape[0]
    M = _np.vstack([_commutator_map(G), _tp_row_constraints(n)])
    ns = _spl.null_space(M, rcond=tol)
    return [ns[:, i].reshape(n, n) for i in range(ns.shape[1])]


# ---------------------------------------------------------------------------
# stage 2: the standard gauge
# ---------------------------------------------------------------------------

def standard_gauge_transform(model, target_model, reference_gate, other_gates=None,
                             return_info=False, fix_spam_gauge=True):
    """
    Gauge transformation bringing `model` to the cGST manuscript's *standard gauge*.

    The transformation is built in two stages and returned as `A = A2 @ A1`
    (apply `A1` first):

    * **Stage 1.** `A1 = commuting_gauge_transform(Lam_ref, G_ref)` brings the
      reference gate to the gauge in which its error channel commutes with the ideal
      gate exactly (manuscript App. "Construction of the commuting gauge").

    * **Stage 2.** The residual freedom is the group of TP gauge transformations that
      commute with the ideal reference gate, generated by `tp_commutant_basis(G_ref)`.
      Over this group the summed squared Frobenius norm of the *errors* of the other
      gates,

          sum_g || A2 A1 Lam_g A1^{-1} A2^{-1} - G_g ||_F^2,

      is minimized (manuscript App. "Construction of the standard gauge", which
      phrases this as minimizing the L2 norm of the sqrt(Y) channel; as the commuting
      gauge appendix explains, this is a least-squares removal of the gauge-movable
      part of the error, and the objective used here is the corresponding one with the
      ideal gate subtracted).  For the {S, sqrt(Y)} gate set with reference gate S this
      reproduces the manuscript's construction: the equatorial scale xi, the axis scale
      zeta and the axis shift eta minimize the sqrt(Y) error, and the equatorial
      rotation psi (the manuscript's A_3) is fixed by the same minimization, which
      places the relational coherent error along X, i.e. the sqrt(Y) axis tilt in the
      Y-Z plane.  The optimization starts at the identity, where the objective is
      already close to its minimum because stage 1 tends to the identity as the noise
      vanishes.  The stationary conditions of this objective are, to first order,
      exactly the symmetries of the manuscript's sqrt(Y) channel form: the X and Z
      rows carry equal Ramsey decays (r_2) and equal relational active errors (a_rel),
      with the second-order residuals delta and delta' determined by the minimization.

    Gauge directions that commute with *all* ideal gates (reference and others), e.g.
    the uniform Bloch-ball scaling `diag(0, 1, ..., 1)` for any irreducible gate set,
    do not move any gate at first order, and therefore cannot be fixed by the gate
    errors; worse, they rescale the affine (non-unital) parts of all gates, so the
    Frobenius objective has no minimum along them.  These "SPAM-only" directions are
    split off (they span a normal sub-algebra of the commutant, so the residual group
    factorizes as `A2 = D @ N` with `D` SPAM-only and `N` gate-fixed) and, when
    `fix_spam_gauge` is True, fixed by a nested minimization: for each `D`, `N(D)`
    minimizes the gate objective, and `D` is chosen to minimize the squared distance
    of the transformed preps and POVM effects from the target ones.  This makes the
    overall gauge fixing well posed and invariant under (near-identity) TP gauge
    transformations of the input.  With `fix_spam_gauge=False` these directions are
    left at the identity instead.

    The SPAM tie-break only pins the uniform scaling, however.  When the ideal gate
    set acts *reducibly* on the Bloch space -- e.g. {Z(pi), Y(pi/2)}, whose common
    invariant Y axis gives a second all-gate-commuting direction, the Y-axis scaling,
    that the ideal SPAM cannot see -- there is more than one SPAM-only direction, the
    construction is ill-conditioned and the result is *not* gauge invariant at the
    level of the error rates; a :class:`UserWarning` is issued in that case.

    Parameters
    ----------
    model : Model
        The noisy model (any parameterization; only dense operation matrices, preps
        and POVM effects are read).  Must use the 'pp' basis.

    target_model : Model
        The ideal model, with the same operation labels and basis.

    reference_gate : Label or str
        The gate brought to the commuting gauge in stage 1 (the S gate, `'Gzpi2'`, in
        the manuscript).  A bare gate name is resolved against the target model's
        operation labels.

    other_gates : list of (Label or str), optional
        The gates whose errors are minimized in stage 2.  `None` means all primitive
        gates of the target model other than the reference gate (including an idle, if
        present; pass an explicit list to restrict to, e.g., `['Gypi2']`).

    return_info : bool, optional
        Whether to also return a dictionary with details of the construction.

    fix_spam_gauge : bool, optional
        Whether to fix the SPAM-only gauge directions (see above) using the model's
        SPAM.  If False they are left at the identity.

    Returns
    -------
    A : numpy.ndarray
        Real TP gauge matrix.  Gates transform as `A Lam A^{-1}`, preps as `A |rho>>`
        and effects as `<<E| A^{-1}`.

    info : dict
        Only when `return_info=True`.  Keys: `'stage1'` (A1), `'stage2'` (A2),
        `'basis'` (the full TP-commutant basis), `'gate_fixed_basis'` and
        `'spam_fixed_basis'` (its split into gate-fixed and SPAM-only generators),
        `'gate_params'` and `'spam_params'` (the optimal coefficients in those bases),
        `'gate_objective'` (final value of the summed squared Frobenius error),
        `'optimizer_result'` and `'spam_optimizer_result'` (scipy results or None),
        `'reference_gate'` and `'other_gates'` (resolved labels).
    """
    _check_pp_basis(model)
    _check_pp_basis(target_model)
    ref_lbl = _resolve_gate_label(target_model, reference_gate)
    if other_gates is None:
        other_lbls = [k for k in target_model.operations.keys() if k != ref_lbl]
    else:
        other_lbls = [_resolve_gate_label(target_model, g) for g in other_gates]

    G = {lbl: _dense(target_model.operations[lbl]) for lbl in [ref_lbl] + other_lbls}
    Lam = {lbl: _dense(model.operations[lbl]) for lbl in [ref_lbl] + other_lbls}
    n = G[ref_lbl].shape[0]

    # --- stage 1
    A1 = commuting_gauge_transform(Lam[ref_lbl], G[ref_lbl])
    A1inv = _np.linalg.inv(A1)
    Lam1 = {lbl: A1 @ Lam[lbl] @ A1inv for lbl in other_lbls}

    # --- residual freedom and its split into gate-fixed / SPAM-only generators
    Ks = tp_commutant_basis(G[ref_lbl])
    m = len(Ks)
    if m > 0:
        Kmat = _np.column_stack([K.ravel() for K in Ks])              # n^2 x m
        if len(other_lbls) > 0:
            Mall = _np.vstack([_commutator_map(G[lbl]) @ Kmat for lbl in other_lbls])
            c_spam = _spl.null_space(Mall, rcond=1e-8)                 # m x m_spam
        else:
            c_spam = _np.identity(m)
        c_gate = _orthonormal_complement(c_spam, m)                    # m x m_gate
    else:
        c_spam = _np.zeros((0, 0)); c_gate = _np.zeros((0, 0))
    K_spam = [sum(c_spam[i, j] * Ks[i] for i in range(m)) for j in range(c_spam.shape[1])]
    K_gate = [sum(c_gate[i, j] * Ks[i] for i in range(m)) for j in range(c_gate.shape[1])]
    n_spam, n_gate = len(K_spam), len(K_gate)

    def stage2(p_spam, p_gate):
        D = _expm_combo(p_spam, K_spam) if n_spam > 0 else _np.identity(n)
        N = _expm_combo(p_gate, K_gate) if n_gate > 0 else _np.identity(n)
        return D @ N

    def gate_residuals(p_gate, p_spam):
        A2 = stage2(p_spam, p_gate)
        A2inv = _np.linalg.inv(A2)
        if len(other_lbls) == 0:
            return _np.zeros(0)
        return _np.concatenate([(A2 @ Lam1[lbl] @ A2inv - G[lbl]).ravel() for lbl in other_lbls])

    def gate_jacobian(p_gate, p_spam):
        # Analytic derivative of `gate_residuals` w.r.t. `p_gate`, via the Frechet
        # derivative of the matrix exponential: with N = expm(K(p)), M = N Lam1 N^-1
        # and A2 = D N, d(A2 Lam1 A2^-1) = D [ (dN N^-1) M - M (dN N^-1) ] D^-1.
        D = _expm_combo(p_spam, K_spam) if n_spam > 0 else _np.identity(n)
        Dinv = _np.linalg.inv(D)
        Kp = sum(c * K for c, K in zip(p_gate, K_gate)) if n_gate > 0 else _np.zeros((n, n))
        N = _spl.expm(Kp)
        Ninv = _np.linalg.inv(N)
        Ms = [N @ Lam1[lbl] @ Ninv for lbl in other_lbls]
        cols = []
        for K in K_gate:
            dN = _spl.expm_frechet(Kp, K, compute_expm=False)
            X = dN @ Ninv
            cols.append(_np.concatenate([(D @ (X @ M - M @ X) @ Dinv).ravel() for M in Ms]))
        return _np.column_stack(cols)

    state = {'result': None}

    def solve_gate(p_spam):
        # Stateless: every inner solve starts from the identity, so that the outer
        # (SPAM) objective is a well-defined function of `p_spam` alone rather than of
        # the optimizer's evaluation history.  The analytic Jacobian makes the solve
        # converge to machine precision (a numerically-differentiated one stalls at
        # ~1e-7 in the parameters for this nonzero-residual problem, which would put
        # noise of that size into the outer, SPAM-fixing solve).
        if n_gate == 0 or len(other_lbls) == 0:
            state['result'] = None
            return _np.zeros(n_gate)
        res = _least_squares(gate_residuals, _np.zeros(n_gate), args=(p_spam,), jac=gate_jacobian)
        state['result'] = res
        return res.x

    if n_spam > 1:
        _warnings.warn("standard_gauge_transform: %d gauge directions commute with every ideal "
                       "gate (reference %s, others %s), i.e. the ideal gate set acts reducibly "
                       "and has more all-gate-commuting directions than the uniform Bloch-ball "
                       "scaling.  Only that scaling is pinned by the SPAM tie-break, so the "
                       "standard gauge is ill-conditioned for this gate set / reference gate: "
                       "the reported gauge-fixed model can depend on the gauge of the input at "
                       "the level of the error rates.  Prefer a reference gate and gate set "
                       "whose ideal actions have no common invariant subspace."
                       % (n_spam, str(ref_lbl), [str(l) for l in other_lbls]))

    # --- SPAM data for the tie-break of the SPAM-only directions
    preps, effects = [], []
    if fix_spam_gauge and n_spam > 0:
        for plbl, prep in model.preps.items():
            if plbl in target_model.preps:
                preps.append((_np.asarray(prep.to_dense(), dtype=float).ravel(),
                              _np.asarray(target_model.preps[plbl].to_dense(), dtype=float).ravel()))
        for mlbl, povm in model.povms.items():
            if mlbl in target_model.povms:
                tpovm = target_model.povms[mlbl]
                for elbl, effect in povm.items():
                    if elbl in tpovm:
                        effects.append((_np.asarray(effect.to_dense(), dtype=float).ravel(),
                                        _np.asarray(tpovm[elbl].to_dense(), dtype=float).ravel()))

    def spam_residuals(p_spam):
        p_gate = solve_gate(p_spam)
        A = stage2(p_spam, p_gate) @ A1
        Ainv = _np.linalg.inv(A)
        res = [A @ rho - rho0 for rho, rho0 in preps] + [Ainv.T @ E - E0 for E, E0 in effects]
        return _np.concatenate(res)

    spam_result = None
    if fix_spam_gauge and n_spam > 0 and (len(preps) + len(effects)) > 0:
        # The outer residuals contain a nested numerical solve, so their finite-
        # difference Jacobian needs a step well above that solve's convergence
        # noise (~1e-14 in the parameters); the objective is smooth on the 1e-6 scale.
        spam_result = _least_squares(spam_residuals, _np.zeros(n_spam), diff_step=1e-6)
        p_spam = spam_result.x
    else:
        if fix_spam_gauge and n_spam > 0:
            _warnings.warn("standard_gauge_transform: no SPAM shared with the target model; "
                           "the %d SPAM-only gauge direction(s) are left at the identity" % n_spam)
        p_spam = _np.zeros(n_spam)
    p_gate = solve_gate(p_spam)  # (re)solve at the final SPAM parameters
    A2 = stage2(p_spam, p_gate)
    A = A2 @ A1
    A[0, :] = 0.0; A[0, 0] = 1.0  # exact TP (A1 and expm of zero-first-row generators are TP)

    if not return_info:
        return A
    gate_res = gate_residuals(p_gate, p_spam)
    info = {'stage1': A1, 'stage2': A2, 'basis': Ks,
            'gate_fixed_basis': K_gate, 'spam_fixed_basis': K_spam,
            'gate_params': p_gate, 'spam_params': p_spam,
            'gate_objective': float(_np.dot(gate_res, gate_res)),
            'optimizer_result': state['result'], 'spam_optimizer_result': spam_result,
            'reference_gate': ref_lbl, 'other_gates': other_lbls}
    return A, info


def fix_standard_gauge(model, target_model, reference_gate, other_gates=None, fix_spam_gauge=True):
    """
    Return a copy of `model` in the cGST standard gauge.

    The copy is converted to dense `'full TP'` operations, states and POVMs, and then
    gauge transformed by :func:`standard_gauge_transform`: gates become
    `A Lam A^{-1}`, preps `A |rho>>` and effects `<<E| A^{-1}`.

    Parameters
    ----------
    model : Model
        The noisy model (any parameterization, 'pp' basis).

    target_model : Model
        The ideal model with the same operation labels.

    reference_gate : Label or str
        Gate brought to the commuting gauge (e.g. `'Gzpi2'`).

    other_gates : list, optional
        Gates whose errors are minimized in stage 2; `None` means all other gates.

    fix_spam_gauge : bool, optional
        See :func:`standard_gauge_transform`.

    Returns
    -------
    ExplicitOpModel
    """
    mdl = model.copy()
    mdl.set_all_parameterizations('full TP')
    A = standard_gauge_transform(mdl, target_model, reference_gate, other_gates,
                                 fix_spam_gauge=fix_spam_gauge)
    # pyGSTi's convention is G -> S^{-1} G S, rho -> S^{-1} rho, E -> E S; we want A Lam A^{-1}.
    mdl.transform_inplace(_FullGaugeGroupElement(_np.linalg.inv(A)))
    return mdl


# ---------------------------------------------------------------------------
# reporting: elementary error-generator coefficients
# ---------------------------------------------------------------------------

def errorgen_coefficients_in_gauge(model, target_model, errorgen_types=('H', 'S', 'C', 'A')):
    """
    Elementary error-generator coefficients of every gate of `model`, in its current gauge.

    For each primitive gate of `target_model`, the error generator
    `L = log(Lam G^{-1})` ('logGTi' convention, so that `Lam = exp(L) G`) is computed
    with :func:`pygsti.tools.optools.error_generator` and projected onto the
    elementary error generators of Blume-Kohout et al. (H, S, C, A types, 'PP'
    elementary basis) via `LindbladErrorgen.from_error_generator(..., 'GLND')`.  The
    coefficients use the plain (non-logscale) convention, so that they agree with the
    `lindblad_error_coeffs` accepted by :func:`pygsti.models.modelconstruction.create_explicit_model`.
    Because the elementary error generators form a complete basis of TP generators,
    each coefficient is independent of which `errorgen_types` are requested.

    Parameters
    ----------
    model : Model
        The (gauge-fixed) noisy model, 'pp' basis.

    target_model : Model
        The ideal model with the same operation labels.

    errorgen_types : tuple of str, optional
        Which error-generator sectors to report ('H', 'S', 'C', 'A').

    Returns
    -------
    dict
        `{gate_label: {GlobalElementaryErrorgenLabel: float}}`.
    """
    _check_pp_basis(model)
    _check_pp_basis(target_model)
    errorgen_types = tuple(errorgen_types)
    out = {}
    for lbl, tgt_op in target_model.operations.items():
        if lbl not in model.operations:
            continue
        Gmx = _dense(tgt_op)
        Lmx = _dense(model.operations[lbl])
        errgen = _ot.error_generator(Lmx, Gmx, model.basis, 'logGTi')
        eg = _LindbladErrorgen.from_error_generator(errgen, 'GLND', 'PP', model.basis, truncate=True,
                                                    state_space=target_model.state_space)
        coeffs = {}
        for key, val in eg.coefficients(label_type='global').items():
            if key.errorgen_type not in errorgen_types:
                continue
            if abs(_np.imag(val)) > 1e-8:
                raise ValueError("Non-real error generator coefficient %s for gate %s" % (key, lbl))
            coeffs[key] = float(_np.real(val))
        out[lbl] = coeffs
    return out
