#!/usr/bin/env python3
import multiprocessing
import subprocess
import sys


def main(args):
    assert len(args) > 0
    N = multiprocessing.cpu_count()
    subprocess.call(['mpiexec', '-n', str(N)] + args)

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
