"""
Virtual-qubit ("gadget") representation of mid-circuit measurements for error generator propagation.
"""
#***************************************************************************************************
# Copyright 2015, 2019, 2025 National Technology & Engineering Solutions of Sandia, LLC (NTESS).
# Under the terms of Contract DE-NA0003525 with NTESS, the U.S. Government retains certain rights
# in this software.
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.  You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0 or in the LICENSE file in the root pyGSTi directory.
#***************************************************************************************************
"""
Overview
--------
A noisy computational-basis mid-circuit measurement (MCM) of a qubit ``q`` is modelled, following
Wysocki et al. (arXiv:2602.03938), by a *circuit gadget* acting on the data qubits plus one
auxiliary *virtual* qubit ``v``:

1. ideal preparation of ``v`` in :math:`|0\\rangle`,
2. an ideal CNOT with ``q`` as control and ``v`` as target,
3. a post-CNOT error channel :math:`e^{L}` generated by a Lindbladian ``L`` on (data qubits + ``v``),
4. an ideal terminating Z-basis measurement of ``v``, whose result is the MCM outcome ``c``.

The resulting quantum instrument is :math:`Q_c = (I \\otimes \\langle\\langle c|) e^{L}
\\,\\mathrm{CNOT}\\,(I \\otimes |0\\rangle\\rangle)`, and to first order in the error rates the
*deviation* from the ideal projective instrument is the linear ("crunch") map
:math:`\\Delta Q_c = (I \\otimes \\langle\\langle c|) L \\,\\mathrm{CNOT}\\,(I \\otimes |0\\rangle\\rangle)`.

Because every ingredient of the gadget is a stabilizer operation, a circuit containing ``m``
MCMs on ``n`` qubits maps onto an ordinary *Clifford* circuit on ``n + m`` qubits in which each
MCM is replaced by a CNOT onto a fresh virtual qubit (this is just the deferred-measurement
principle).  The terminating computational-basis measurement of the enlarged circuit then
records the *joint* (final bitstring, MCM outcomes) distribution, and the existing error
generator propagation / first-order sensitivity machinery (:mod:`pygsti.tools.errgenproptools`)
can be applied to MCM circuits without modification.  This module provides:

* :func:`expand_mcm_circuit` -- the circuit-level gadget substitution,
* :func:`joint_outcome_to_bitstring` -- conversion of pyGSTi's MCM outcome tuples to bitstrings
  of the enlarged system,
* dense constructions of the gadget generator, the noisy instrument members and pyGSTi
  :class:`~pygsti.modelmembers.instruments.Instrument` objects (for simulation),
* the first-order crunch map, its null space (the *MCM gauge*) and the *first-order
  MCM-gauge-invariant (FOMGI)* quantities of Wysocki et al.

Conventions
-----------
* Gadget Pauli strings list the gadget's data qubit(s) first and the virtual qubit *last*; e.g. for
  the standard one-data-qubit gadget, ``'ZY'`` means ``Z`` on the measured qubit and ``Y`` on the
  virtual qubit (so ``S_IX`` is a pure readout error and ``H_ZY`` a "unitary weakness").
* Error generators use pyGSTi's conventions, ``H_P[rho] = -i[P, rho]`` and
  ``S_P[rho] = P rho P - rho`` with *unnormalized* Paulis, matching :class:`LindbladErrorgen`.
* Virtual qubits are appended after the data qubits, in MCM order (layer order first, then
  component order within a layer, then qubit order within a multi-qubit instrument label), which
  matches the ordering of instrument outcomes in pyGSTi outcome-label tuples.
"""

import collections as _collections
import itertools as _itertools
import warnings as _warnings

import numpy as _np
import scipy.linalg as _spl

from pygsti.baseobjs.label import Label as _Label, CircuitLabel as _CircuitLabel
from pygsti.baseobjs.basis import BuiltinBasis as _BuiltinBasis
from pygsti.baseobjs.statespace import QubitSpace as _QubitSpace, StateSpace as _StateSpace
from pygsti.baseobjs.errorgenlabel import LocalElementaryErrorgenLabel as _LEEL, \
    GlobalElementaryErrorgenLabel as _GEEL
from pygsti.circuits.circuit import Circuit as _Circuit
from pygsti.tools import optools as _ot
from pygsti.tools import basistools as _bt
from pygsti.tools import internalgates as _itgs

#: Token used inside error-generator specifications (e.g. ``'XX:1,v'``) to denote the virtual qubit.
VIRTUAL_QUBIT_TOKEN = 'v'

#: Default instrument (gate) names that are interpreted as computational-basis mid-circuit measurements.
DEFAULT_MCM_GATE_NAMES = ('Iz',)

#: Bookkeeping record for one measured qubit of an MCM inside a circuit.
MCMInfo = _collections.namedtuple('MCMInfo', ['layer_index', 'component_index', 'mcm_index',
                                              'data_qubit', 'virtual_qubit'])
MCMInfo.__doc__ = """Describes a single measured qubit of a mid-circuit measurement in a circuit.

Attributes
----------
layer_index : int
    Index of the circuit layer containing the MCM.
component_index : int
    Index of the instrument label within that layer's components.
mcm_index : int
    Running index of this measured qubit among all MCMs of the circuit (0-based).  Virtual qubit
    number `mcm_index` is appended after the data qubits in the expanded circuit.
data_qubit : hashable
    Line label of the measured (data) qubit.
virtual_qubit : hashable
    Line label of the virtual qubit that stores the MCM outcome in the expanded circuit.
"""


# ---------------------------------------------------------------------------------------------------
# Circuit-level gadget substitution
# ---------------------------------------------------------------------------------------------------

def is_mcm_label(lbl, mcm_gate_names=DEFAULT_MCM_GATE_NAMES):
    """
    Whether a (component) label denotes a mid-circuit measurement.

    Parameters
    ----------
    lbl : Label
        A circuit-layer component label.

    mcm_gate_names : iterable of str, optional
        The instrument names to treat as computational-basis mid-circuit measurements.

    Returns
    -------
    bool
    """
    return getattr(lbl, 'name', None) in mcm_gate_names


def mcm_infos(circuit, mcm_gate_names=DEFAULT_MCM_GATE_NAMES, virtual_labels=None):
    """
    Enumerate the mid-circuit measurements of a circuit (one record per measured qubit).

    Parameters
    ----------
    circuit : Circuit
        The circuit to inspect.

    mcm_gate_names : iterable of str, optional
        The instrument names to treat as computational-basis mid-circuit measurements.

    virtual_labels : list, optional
        Line labels to use for the virtual qubits (one per measured qubit, in MCM order).  If
        None they are generated by :func:`virtual_qubit_labels`.

    Returns
    -------
    list of MCMInfo
    """
    line_labels = circuit.line_labels
    infos = []
    for layer_index, layer_lbl in enumerate(circuit):
        for component_index, comp in enumerate(layer_lbl.components):
            if not is_mcm_label(comp, mcm_gate_names):
                continue
            qubits = comp.sslbls if comp.sslbls is not None else tuple(line_labels)
            for q in qubits:
                infos.append(MCMInfo(layer_index, component_index, len(infos), q, None))
    if virtual_labels is None:
        virtual_labels = virtual_qubit_labels(line_labels, len(infos))
    assert len(virtual_labels) >= len(infos), "Not enough virtual qubit labels supplied!"
    return [info._replace(virtual_qubit=virtual_labels[info.mcm_index]) for info in infos]


def num_mcms(circuit, mcm_gate_names=DEFAULT_MCM_GATE_NAMES):
    """
    The number of measured qubits in mid-circuit measurements of `circuit` (= number of virtual qubits).

    Parameters
    ----------
    circuit : Circuit
    mcm_gate_names : iterable of str, optional

    Returns
    -------
    int
    """
    count = 0
    for layer_lbl in circuit:
        for comp in layer_lbl.components:
            if is_mcm_label(comp, mcm_gate_names):
                count += len(comp.sslbls) if comp.sslbls is not None else len(circuit.line_labels)
    return count


def virtual_qubit_labels(line_labels, num_virtual):
    """
    Generate line labels for virtual qubits that do not collide with the given data-qubit labels.

    If all data labels are integers the virtual labels are the next unused integers, otherwise
    they are strings of the form ``'v0', 'v1', ...`` (skipping any that are already in use).

    Parameters
    ----------
    line_labels : tuple
        The data-qubit line labels.

    num_virtual : int
        The number of virtual qubit labels to generate.

    Returns
    -------
    list
    """
    if num_virtual == 0:
        return []
    existing = set(line_labels)
    if len(line_labels) > 0 and all(isinstance(l, (int, _np.integer)) for l in line_labels):
        start = max(int(l) for l in line_labels) + 1
        return [start + k for k in range(num_virtual)]
    labels = []
    k = 0
    while len(labels) < num_virtual:
        cand = '%s%d' % (VIRTUAL_QUBIT_TOKEN, k)
        if cand not in existing:
            labels.append(cand)
        k += 1
    return labels


def expand_mcm_circuit(circuit, mcm_gate_names=DEFAULT_MCM_GATE_NAMES, cnot_name='Gcnot',
                       virtual_labels=None):
    """
    Replace every mid-circuit measurement by a CNOT onto a fresh virtual qubit (deferred measurement).

    Each measured qubit ``q`` of an instrument label in `circuit` is replaced by ``Label(cnot_name, (q, v))``
    where ``v`` is a new virtual qubit line appended after the data qubits.  The measurement of ``v`` is
    deferred to the end of the circuit, so the terminating computational-basis measurement of the
    returned circuit yields the joint distribution of the original circuit's final bitstring and MCM
    outcomes (see :func:`joint_outcome_to_bitstring` for the bit ordering).

    Parameters
    ----------
    circuit : Circuit
        A circuit whose layers may contain instrument labels (e.g. ``Label('Iz', 0)``).  Circuits
        containing :class:`CircuitLabel` sub-circuits are not supported.

    mcm_gate_names : iterable of str, optional
        Instrument names treated as computational-basis mid-circuit measurements.

    cnot_name : str, optional
        Name of the (ideal) controlled-NOT gate used in the gadget.

    virtual_labels : list, optional
        Line labels for the virtual qubits; generated by :func:`virtual_qubit_labels` if None.

    Returns
    -------
    expanded_circuit : Circuit
        Clifford circuit on ``n + m`` lines (data lines first, then virtual lines in MCM order).
    infos : list of MCMInfo
        One record per measured qubit, in MCM order (= virtual-qubit order).
    """
    infos = mcm_infos(circuit, mcm_gate_names, virtual_labels)
    new_line_labels = tuple(circuit.line_labels) + tuple(info.virtual_qubit for info in infos)
    if len(infos) == 0:
        return circuit.copy(editable=False), infos

    info_iter = iter(infos)
    new_layers = []
    for layer_index, layer_lbl in enumerate(circuit):
        if isinstance(layer_lbl, _CircuitLabel) or any(isinstance(c, _CircuitLabel) for c in layer_lbl.components):
            raise NotImplementedError("Circuits with CircuitLabel sub-circuits are not supported by "
                                      "expand_mcm_circuit; expand them first.")
        new_components = []
        for comp in layer_lbl.components:
            if is_mcm_label(comp, mcm_gate_names):
                qubits = comp.sslbls if comp.sslbls is not None else tuple(circuit.line_labels)
                for q in qubits:
                    info = next(info_iter)
                    assert info.data_qubit == q and info.layer_index == layer_index
                    new_components.append(_Label(cnot_name, (q, info.virtual_qubit)))
            else:
                new_components.append(comp)
        if len(new_components) == 1:
            new_layers.append(new_components[0])
        else:
            new_layers.append(_Label(new_components))
    return _Circuit(new_layers, line_labels=new_line_labels), infos


def joint_outcome_to_bitstring(outcome):
    """
    Convert a pyGSTi outcome label of a circuit with mid-circuit measurements into a bitstring of the
    expanded (data + virtual qubits) system.

    pyGSTi outcome labels are tuples ``(mcm_1, ..., mcm_m, final)`` where each ``mcm_k`` is the member
    key of an instrument (here required to be a bitstring such as ``'0'`` or ``'01'``) and ``final`` is
    the terminating-measurement bitstring over the data qubits.  The returned bitstring is
    ``final + mcm_1 + ... + mcm_m``, i.e. data bits first followed by the MCM outcomes in MCM order,
    matching the line ordering of :func:`expand_mcm_circuit`.

    Parameters
    ----------
    outcome : tuple of str or str
        An outcome label.  A plain string (or length-1 tuple) is returned unchanged.

    Returns
    -------
    str
    """
    if isinstance(outcome, str):
        bits = outcome
    else:
        outcome = tuple(outcome)
        bits = outcome[-1] + ''.join(outcome[:-1])
    if not all(ch in '01' for ch in bits):
        raise ValueError(("Cannot interpret outcome label %s as a bitstring of the expanded system. "
                          "Instrument member keys must be bitstrings (e.g. '0'/'1').") % str(outcome))
    return bits


def joint_outcome_probabilities_to_bitstring_dict(prob_dict):
    """
    Re-key a ``{outcome_label: probability}`` dictionary by expanded-system bitstrings.

    Parameters
    ----------
    prob_dict : dict
        Dictionary (e.g. an :class:`OutcomeLabelDict` from :meth:`Model.probabilities`) whose keys are
        outcome labels of a circuit with (or without) mid-circuit measurements.

    Returns
    -------
    dict
        Maps bitstrings (see :func:`joint_outcome_to_bitstring`) to probabilities.
    """
    ret = {}
    for outcome, p in prob_dict.items():
        b = joint_outcome_to_bitstring(outcome)
        ret[b] = ret.get(b, 0.0) + p
    return ret


# ---------------------------------------------------------------------------------------------------
# Dense gadget constructions (pp basis)
# ---------------------------------------------------------------------------------------------------

_PP_UNNORMALIZED_1Q = None


def _pp1q_unnormalized():
    global _PP_UNNORMALIZED_1Q
    if _PP_UNNORMALIZED_1Q is None:
        _PP_UNNORMALIZED_1Q = _BuiltinBasis('PP', 4)  # *unnormalized* Pauli-product basis
    return _PP_UNNORMALIZED_1Q


def _normalize_errorgen_key(key):
    """Convert a user-facing error generator key into an `(errorgen_type, basis_element_labels)` pair."""
    if isinstance(key, _LEEL):
        return key.errorgen_type, tuple(key.basis_element_labels)
    if isinstance(key, _GEEL):
        raise ValueError("GlobalElementaryErrorgenLabel keys are ambiguous for the gadget; use local "
                         "labels / (type, pauli-string) tuples whose last character is the virtual qubit.")
    if hasattr(key, 'errorgen_type') and hasattr(key, 'basis_element_labels'):  # e.g. LocalStimErrorgenLabel
        bels = tuple(str(p)[1:].replace('_', 'I') if not isinstance(p, str) else p
                     for p in key.basis_element_labels)
        return key.errorgen_type, bels
    key = tuple(key)
    typ = key[0]
    if len(key) == 2 and isinstance(key[1], (tuple, list)):  # (type, (bel1[, bel2])) form
        bels = tuple(key[1])
    else:  # (type, bel1[, bel2]) form
        bels = tuple(key[1:])
    if typ not in ('H', 'S', 'C', 'A'):
        raise ValueError("Unrecognized error generator type '%s'" % str(typ))
    if typ in ('H', 'S') and len(bels) != 1 or typ in ('C', 'A') and len(bels) != 2:
        raise ValueError("Wrong number of basis element labels for error generator %s" % str(key))
    return typ, bels


def elementary_errorgen_matrix(errorgen_type, basis_element_labels, mx_basis='pp'):
    """
    Dense matrix of an elementary error generator with *unnormalized* Pauli basis elements.

    This matches the rate convention of :class:`LindbladErrorgen` and of the first-order sensitivity
    functions in :mod:`pygsti.tools.errgenproptools`.

    Parameters
    ----------
    errorgen_type : {'H', 'S', 'C', 'A'}
    basis_element_labels : tuple of str
        Pauli strings (all of the same length), one for 'H'/'S' and two for 'C'/'A'.
    mx_basis : Basis or str, optional
        Basis of the returned superoperator matrix.

    Returns
    -------
    numpy.ndarray
    """
    mx_std = _ot.create_elementary_errorgen_nqudit(errorgen_type, tuple(basis_element_labels), _pp1q_unnormalized())
    return _bt.change_basis(mx_std, 'std', mx_basis)


def mcm_gadget_errorgen(errorgen_rates, num_gadget_data_qubits=1, mx_basis='pp'):
    """
    Dense Lindbladian of the MCM gadget on (gadget data qubits + virtual qubit).

    Parameters
    ----------
    errorgen_rates : dict
        Maps error generator specifications to rates.  Keys may be ``(type, pauli)`` / ``(type, pauli1, pauli2)``
        tuples or :class:`LocalElementaryErrorgenLabel` objects, whose Pauli strings have length
        ``num_gadget_data_qubits + 1`` with the virtual qubit *last*.

    num_gadget_data_qubits : int, optional
        Number of data qubits the gadget acts on (1 for the standard single-qubit MCM gadget).

    mx_basis : Basis or str, optional
        Basis of the returned matrix.

    Returns
    -------
    numpy.ndarray
        A ``4**(k+1) x 4**(k+1)`` matrix, ``k = num_gadget_data_qubits``.
    """
    nq = num_gadget_data_qubits + 1
    L = _np.zeros((4**nq, 4**nq), dtype=complex)
    for key, rate in errorgen_rates.items():
        typ, bels = _normalize_errorgen_key(key)
        if any(len(b) != nq for b in bels):
            raise ValueError("Gadget error generator %s must have Pauli strings of length %d (data qubits + "
                             "virtual qubit)" % (str(key), nq))
        L += rate * elementary_errorgen_matrix(typ, bels, mx_basis)
    if _np.allclose(L.imag, 0):
        L = L.real
    return L


def _gadget_ops(num_gadget_data_qubits, measured_index):
    """(prep, cnot, {c: proj_c}) dense pp-basis operators for the gadget (virtual qubit last)."""
    k = num_gadget_data_qubits
    if not (0 <= measured_index < k):
        raise ValueError("measured_index must index one of the %d gadget data qubits" % k)
    ss = _QubitSpace(k + 1)
    # ideal CNOT from data qubit `measured_index` (control) to the virtual qubit (target)
    cnot_2q = _ot.unitary_to_superop(_itgs.standard_gatename_unitaries()['Gcnot'], 'pp')
    from pygsti.modelmembers.operations import EmbeddedOp as _EmbeddedOp, StaticArbitraryOp as _StaticArbitraryOp
    cnot = _EmbeddedOp(ss, (measured_index, k), _StaticArbitraryOp(cnot_2q, basis='pp')).to_dense()

    def superket(vec):
        return _bt.change_basis(_ot.state_to_dmvec(_np.array(vec, dtype=complex)), 'std', 'pp').real

    eye = _np.eye(4**k)
    prep = _np.kron(eye, superket([1, 0]).reshape(4, 1))
    proj = {'0': _np.kron(eye, superket([1, 0]).reshape(1, 4)),
            '1': _np.kron(eye, superket([0, 1]).reshape(1, 4))}
    return prep, cnot, proj


def mcm_gadget_crunch(gadget_superop, num_gadget_data_qubits=1, measured_index=0):
    """
    Apply the gadget's "crunch" map to a superoperator on (gadget data qubits + virtual qubit).

    Computes ``{c: (I ⊗ <<c|) E CNOT (I ⊗ |0>>)}`` for ``c in ('0', '1')``.  With ``E = exp(L)`` this
    gives the noisy instrument members; with ``E = L`` it gives the first-order instrument deviation.

    Parameters
    ----------
    gadget_superop : numpy.ndarray
        ``4**(k+1) x 4**(k+1)`` matrix in the pp basis (virtual qubit last).
    num_gadget_data_qubits : int, optional
    measured_index : int, optional
        Index (among the gadget data qubits) of the measured qubit = CNOT control.

    Returns
    -------
    dict
        Maps ``'0'`` and ``'1'`` to ``4**k x 4**k`` matrices (pp basis) on the gadget data qubits.
    """
    prep, cnot, proj = _gadget_ops(num_gadget_data_qubits, measured_index)
    return {c: proj[c] @ gadget_superop @ cnot @ prep for c in ('0', '1')}


def mcm_gadget_instrument_members(errorgen_rates, num_gadget_data_qubits=1, measured_index=0, first_order=False):
    """
    Dense (pp basis) members of the noisy instrument produced by the MCM gadget.

    Parameters
    ----------
    errorgen_rates : dict
        See :func:`mcm_gadget_errorgen`.  An empty dict gives the ideal projective instrument.
    num_gadget_data_qubits : int, optional
    measured_index : int, optional
        Index (among the gadget data qubits) of the measured qubit.
    first_order : bool, optional
        If True use ``I + L`` instead of ``exp(L)`` (the linearized instrument).

    Returns
    -------
    dict
        ``{'0': Q_0, '1': Q_1}`` with ``4**k x 4**k`` real matrices.
    """
    L = mcm_gadget_errorgen(errorgen_rates, num_gadget_data_qubits, 'pp')
    E = _np.eye(L.shape[0]) + L if first_order else _spl.expm(L)
    members = mcm_gadget_crunch(E, num_gadget_data_qubits, measured_index)
    return {c: (m.real if _np.allclose(m.imag, 0) else m) for c, m in members.items()}


def mcm_gadget_instrument(errorgen_rates, state_space, measured_qubit, gadget_qubits=None, evotype='default',
                          first_order=False):
    """
    Build a pyGSTi :class:`Instrument` for a noisy MCM from gadget error-generator rates.

    The instrument members are :class:`EmbeddedOp` (static) operators acting on the full `state_space`,
    so the instrument can be inserted directly into an n-qubit model, e.g.
    ``model.instrument_blks['layers'][Label('Iz', q)] = inst`` for local/cloud noise models (see
    :func:`insert_mcm_gadget_instrument`).

    Parameters
    ----------
    errorgen_rates : dict
        Gadget error generator rates; Pauli strings have length ``len(gadget_qubits) + 1`` with the
        virtual qubit last and the data qubits ordered as in `gadget_qubits`.
    state_space : StateSpace or QubitProcessorSpec or list
        The full state space of the model (or its qubit labels).
    measured_qubit : hashable
        Label of the measured qubit.
    gadget_qubits : list, optional
        Data qubits the gadget error generator acts on (must contain `measured_qubit`).  Defaults to
        ``[measured_qubit]``.
    evotype : Evotype or str, optional
    first_order : bool, optional
        If True the members are computed from ``I + L`` rather than ``exp(L)``.

    Returns
    -------
    Instrument
    """
    from pygsti.modelmembers.operations import EmbeddedOp as _EmbeddedOp, StaticArbitraryOp as _StaticArbitraryOp
    from pygsti.modelmembers.instruments import Instrument as _Instrument

    if isinstance(state_space, _StateSpace):
        ss = state_space
    elif hasattr(state_space, 'qubit_labels'):  # processor spec
        ss = _QubitSpace(state_space.qubit_labels)
    else:
        ss = _QubitSpace(list(state_space))

    gadget_qubits = [measured_qubit] if gadget_qubits is None else list(gadget_qubits)
    if measured_qubit not in gadget_qubits:
        raise ValueError("`gadget_qubits` must contain the measured qubit")
    members = mcm_gadget_instrument_members(errorgen_rates, len(gadget_qubits), gadget_qubits.index(measured_qubit),
                                            first_order=first_order)
    gadget_ss = _QubitSpace(gadget_qubits)
    inst_members = _collections.OrderedDict()
    for c, mx in members.items():
        local_op = _StaticArbitraryOp(mx, basis='pp', evotype=evotype, state_space=gadget_ss)
        if tuple(gadget_qubits) == tuple(ss.qubit_labels):
            inst_members[c] = local_op
        else:
            inst_members[c] = _EmbeddedOp(ss, tuple(gadget_qubits), local_op)
    return _Instrument(inst_members, evotype=evotype, state_space=ss)


def mcm_gadget_product_instrument(errorgen_rates_by_qubit, state_space, gadget_qubits_by_qubit=None,
                                  evotype='default', first_order=False):
    """
    Instrument for the simultaneous MCM of several qubits: the tensor product of single-qubit gadget instruments.

    Member keys are the concatenated single-qubit outcomes in the order of `errorgen_rates_by_qubit`
    (e.g. ``'01'``), matching pyGSTi's outcome convention for multi-qubit ``'Iz'`` instruments.

    Parameters
    ----------
    errorgen_rates_by_qubit : dict
        Maps each measured qubit label to its gadget error generator rates (see :func:`mcm_gadget_instrument`).
    state_space : StateSpace or QubitProcessorSpec or list
    gadget_qubits_by_qubit : dict, optional
        Maps measured qubits to the data qubits their gadget acts on (default: only the measured qubit).
    evotype : Evotype or str, optional
    first_order : bool, optional

    Returns
    -------
    Instrument
    """
    from pygsti.modelmembers.operations import ComposedOp as _ComposedOp
    from pygsti.modelmembers.instruments import Instrument as _Instrument
    measured = list(errorgen_rates_by_qubit.keys())
    gadget_qubits_by_qubit = {} if gadget_qubits_by_qubit is None else gadget_qubits_by_qubit
    single = {q: mcm_gadget_instrument(errorgen_rates_by_qubit[q], state_space, q, gadget_qubits_by_qubit.get(q, None),
                                       evotype=evotype, first_order=first_order) for q in measured}
    ss = next(iter(single.values())).state_space
    members = _collections.OrderedDict()
    for combo in _itertools.product('01', repeat=len(measured)):
        ops = [single[q][c].copy() for q, c in zip(measured, combo)]
        members[''.join(combo)] = _ComposedOp(ops, evotype=evotype, state_space=ss)
    return _Instrument(members, evotype=evotype, state_space=ss)


def insert_mcm_gadget_instrument(model, measured_qubit, errorgen_rates, gadget_qubits=None,
                                 mcm_gate_name=DEFAULT_MCM_GATE_NAMES[0], first_order=False):
    """
    Insert a gadget-generated noisy MCM instrument into a model under the label ``(mcm_gate_name, measured_qubit)``.

    Works for implicit (local/cloud noise) models via ``model.instrument_blks['layers']`` and for explicit
    models via ``model.instruments`` (in which case auto-embedding of the instruments dictionary is disabled
    since the constructed instrument already acts on the full state space).

    .. note::
       pyGSTi's map forward simulator cannot currently create layouts for implicit models containing
       instruments; use ``simulator='matrix'`` when constructing models that will be simulated with MCMs.

    Parameters
    ----------
    model : Model
    measured_qubit : hashable or tuple
        The measured qubit, or a tuple of qubits for a simultaneous multi-qubit measurement (in which case
        `errorgen_rates` must be a dict mapping each qubit to its gadget rates, see
        :func:`mcm_gadget_product_instrument`).
    errorgen_rates : dict
        See :func:`mcm_gadget_instrument`.
    gadget_qubits : list or dict, optional
    mcm_gate_name : str, optional
    first_order : bool, optional

    Returns
    -------
    Instrument
        The inserted instrument.
    """
    if isinstance(measured_qubit, (tuple, list)):
        inst = mcm_gadget_product_instrument({q: errorgen_rates[q] for q in measured_qubit}, model.state_space,
                                             gadget_qubits, evotype=model.evotype, first_order=first_order)
        key = _Label(mcm_gate_name, tuple(measured_qubit))
    else:
        inst = mcm_gadget_instrument(errorgen_rates, model.state_space, measured_qubit, gadget_qubits,
                                     evotype=model.evotype, first_order=first_order)
        key = _Label(mcm_gate_name, (measured_qubit,))
    if hasattr(model, 'instrument_blks'):
        if 'layers' not in model.instrument_blks:
            from pygsti.models.memberdict import OrderedMemberDict as _OrderedMemberDict
            model.instrument_blks['layers'] = _OrderedMemberDict(model, None, None, {})
        model.instrument_blks['layers'][key] = inst
    else:
        model.instruments.flags['auto_embed'] = False
        model.instruments[key] = inst
    return inst


# ---------------------------------------------------------------------------------------------------
# First-order crunch map, MCM gauge and FOMGI quantities
# ---------------------------------------------------------------------------------------------------

def mcm_crunch_matrix(errorgen_labels, num_gadget_data_qubits=1, measured_index=0):
    """
    Matrix of the first-order map from gadget error-generator rates to instrument deviations.

    Column ``j`` is the concatenation of ``vec(ΔQ_0)`` and ``vec(ΔQ_1)`` (row-major, pp basis) where
    ``ΔQ_c = (I ⊗ <<c|) L_j CNOT (I ⊗ |0>>)`` for the ``j``-th elementary error generator.  Its null space
    is the *MCM gauge* (gadget errors with no first-order effect on the instrument) and its row space
    spans the identifiable (FOMGI) combinations.

    Parameters
    ----------
    errorgen_labels : list
        Error generator specifications (see :func:`mcm_gadget_errorgen` for accepted formats).
    num_gadget_data_qubits : int, optional
    measured_index : int, optional

    Returns
    -------
    numpy.ndarray
        Shape ``(2 * 16**k, len(errorgen_labels))``.
    """
    cols = []
    for lbl in errorgen_labels:
        typ, bels = _normalize_errorgen_key(lbl)
        dev = mcm_gadget_crunch(elementary_errorgen_matrix(typ, bels, 'pp'), num_gadget_data_qubits, measured_index)
        cols.append(_np.concatenate([dev['0'].ravel(), dev['1'].ravel()]))
    F = _np.array(cols).T if len(cols) > 0 else _np.zeros((2 * 16**num_gadget_data_qubits, 0))
    return F.real if _np.allclose(F.imag, 0) else F


def mcm_gauge_directions(errorgen_labels, num_gadget_data_qubits=1, measured_index=0, tol=1e-10):
    """
    Orthonormal basis of the MCM gauge: combinations of gadget error generators with no first-order effect
    on the instrument.

    Parameters
    ----------
    errorgen_labels : list
    num_gadget_data_qubits : int, optional
    measured_index : int, optional
    tol : float, optional
        Singular values below `tol` are treated as zero.

    Returns
    -------
    numpy.ndarray
        Shape ``(len(errorgen_labels), gauge_dimension)``; each column is a null vector (coefficients
        indexed like `errorgen_labels`).
    """
    F = mcm_crunch_matrix(errorgen_labels, num_gadget_data_qubits, measured_index)
    return _spl.null_space(F, rcond=tol)


def mcm_identifiable_directions(errorgen_labels, num_gadget_data_qubits=1, measured_index=0, tol=1e-10):
    """
    Orthonormal basis of the row space of the crunch map: the first-order identifiable combinations of the
    given gadget error generators (the orthogonal complement of the MCM gauge).

    Returns
    -------
    numpy.ndarray
        Shape ``(len(errorgen_labels), rank)``.
    """
    F = mcm_crunch_matrix(errorgen_labels, num_gadget_data_qubits, measured_index)
    if F.shape[1] == 0:
        return _np.zeros((0, 0))
    return _spl.orth(F.T, rcond=tol)


#: Representative elementary error generators defining the 28 elementary instrument deviations
#: (FOMGI quantities) of Wysocki et al., arXiv:2602.03938, Tables 2-7, for the single-qubit MCM gadget
#: (first Pauli character = measured/data qubit, second = virtual qubit).  The deviation associated with
#: each name is the crunch of its representative generator; the deviations are linearly independent and span
#: the full 28-dimensional space of trace-preserving instrument deviations.
FOMGI_REPRESENTATIVES = _collections.OrderedDict([
    # Pauli-stochastic: depolarization during measurement / re-preparation, pure readout error
    ('s_meas', ('S', ('XX',))), ('s_prep', ('S', ('XI',))), ('s_read', ('S', ('IX',))),
    # Active: with S terms generate amplitude damping and measurement bias
    ('a_meas', ('A', ('XX', 'YX'))), ('a_prep', ('A', ('XI', 'YI'))), ('a_read', ('A', ('IX', 'IY'))),
    # Axis rotations (Hamiltonian)
    ('r_meas_x', ('H', ('XX',))), ('r_meas_y', ('H', ('YX',))),
    ('r_prep_x_ind', ('H', ('XI',))), ('r_prep_x_dep', ('H', ('XZ',))),
    ('r_prep_y_ind', ('H', ('YI',))), ('r_prep_y_dep', ('H', ('YZ',))),
    # rho-dependent axis rotations (correlation/active)
    ('rt_meas_x', ('C', ('XI', 'ZY'))), ('rt_meas_y', ('C', ('IX', 'XZ'))),
    ('rt_meas_xz', ('C', ('XZ', 'ZY'))), ('rt_meas_yz', ('C', ('IX', 'XI'))),
    ('rt_prep_x_ind', ('C', ('XX', 'ZY'))), ('rt_prep_x_dep', ('C', ('IX', 'XY'))),
    ('rt_prep_y_ind', ('C', ('IX', 'XX'))), ('rt_prep_y_dep', ('C', ('XX', 'ZX'))),
    # Unitary weakness (incomplete collapse; Hamiltonian)
    ('w0', ('H', ('ZY',))), ('w1', ('H', ('IY',))), ('w2', ('H', ('ZX',))), ('w3', ('H', ('IX',))),
    # Non-unitary weakness (correlation)
    ('wt0', ('C', ('XI', 'XY'))), ('wt1', ('C', ('XI', 'YY'))),
    ('wt2', ('C', ('YY', 'YZ'))), ('wt3', ('C', ('XX', 'XZ'))),
])

#: Sector ('H', 'S', 'C' or 'A') of each named FOMGI quantity, i.e. of its representative generator.
FOMGI_SECTORS = _collections.OrderedDict([(name, typ) for name, (typ, _) in FOMGI_REPRESENTATIVES.items()])


def fomgi_representatives(sectors=('H', 'S')):
    """
    The named FOMGI quantities whose representative generators lie in the given error generator sectors.

    Parameters
    ----------
    sectors : iterable of str or 'all', optional
        Error generator sectors to include (subset of ``('H', 'S', 'C', 'A')``).  With the default
        ``('H', 'S')`` this gives the 13 quantities identifiable from Hamiltonian and Pauli-stochastic
        gadget errors: ``s_meas, s_prep, s_read`` (S) and ``r_meas_x, r_meas_y, r_prep_{x,y}_{ind,dep},
        w0..w3`` (H).

    Returns
    -------
    OrderedDict
        Maps names to ``(errorgen_type, basis_element_labels)`` tuples.
    """
    if sectors == 'all':
        sectors = ('H', 'S', 'C', 'A')
    return _collections.OrderedDict([(name, rep) for name, rep in FOMGI_REPRESENTATIVES.items()
                                     if rep[0] in sectors])


def fomgi_ansatz(sectors=('H', 'S'), rates=None):
    """
    A gadget error model containing one representative generator per FOMGI quantity.

    Using this as the error model of an ``('Iz', q)`` entry in a linearized-GST ansatz gives a set of MCM
    parameters with no MCM-gauge redundancy whose estimated rates are directly the named FOMGI quantities.

    Parameters
    ----------
    sectors : iterable of str or 'all', optional
        See :func:`fomgi_representatives`.
    rates : dict, optional
        Maps FOMGI names to rates; missing names get rate 0.

    Returns
    -------
    OrderedDict
        Maps ``(errorgen_type, pauli_string[, pauli_string])`` keys to rates, in the format accepted as a
        value of the `lindblad_coeff` dictionaries used throughout :mod:`pygsti.algorithms.linearizedgst`.
    """
    rates = {} if rates is None else rates
    reps = fomgi_representatives(sectors)
    unknown = set(rates.keys()) - set(reps.keys())
    if unknown:
        raise ValueError("Unknown FOMGI quantity names (or names outside the requested sectors): %s" % str(unknown))
    return _collections.OrderedDict([((typ,) + tuple(bels), rates.get(name, 0.0))
                                     for name, (typ, bels) in reps.items()])


def fomgi_names_for_ansatz(errorgen_keys):
    """
    Map gadget error generator keys that are FOMGI representatives back to their FOMGI names.

    Parameters
    ----------
    errorgen_keys : iterable
        Error generator keys (see :func:`mcm_gadget_errorgen`).

    Returns
    -------
    dict
        Maps each key that is a representative generator to its FOMGI name.
    """
    lookup = {(typ, tuple(bels)): name for name, (typ, bels) in FOMGI_REPRESENTATIVES.items()}
    ret = {}
    for key in errorgen_keys:
        typ, bels = _normalize_errorgen_key(key)
        if (typ, tuple(bels)) in lookup:
            ret[key] = lookup[(typ, tuple(bels))]
    return ret


def fomgi_decomposition_matrix(errorgen_labels, sectors='auto', measured_index=0):
    """
    Matrix expressing the first-order instrument deviation of each single-qubit-gadget error generator in the
    basis of named FOMGI elementary deviations.

    If ``T`` is the returned matrix and ``eps`` a vector of rates for `errorgen_labels`, then ``T @ eps`` are
    the FOMGI quantities of the gadget error model ``sum_j eps_j L_j`` (to first order).

    Parameters
    ----------
    errorgen_labels : list
        Two-qubit gadget error generator specifications (measured qubit first, virtual qubit second).
    sectors : iterable of str, 'all' or 'auto', optional
        FOMGI quantities to decompose into (see :func:`fomgi_representatives`).  ``'auto'`` uses the 13
        H+S quantities when all `errorgen_labels` are of type 'H' or 'S' and all 28 quantities otherwise.
    measured_index : int, optional
        Index of the measured qubit within the gadget data qubits (only ``0`` is meaningful for the
        single-qubit gadget).

    Returns
    -------
    names : list of str
    T : numpy.ndarray
        Shape ``(len(names), len(errorgen_labels))``.
    """
    typs = [_normalize_errorgen_key(lbl)[0] for lbl in errorgen_labels]
    if sectors == 'auto':
        sectors = ('H', 'S') if all(t in ('H', 'S') for t in typs) else 'all'
    reps = fomgi_representatives(sectors)
    names = list(reps.keys())
    F_rep = mcm_crunch_matrix(list(reps.values()), 1, measured_index)
    F = mcm_crunch_matrix(errorgen_labels, 1, measured_index)
    T, residuals, rank, _ = _np.linalg.lstsq(F_rep, F, rcond=None)
    assert rank == len(names), "FOMGI representative deviations are unexpectedly linearly dependent!"
    if F.shape[1] > 0 and _np.linalg.norm(F_rep @ T - F) > 1e-8 * max(1.0, _np.linalg.norm(F)):
        _warnings.warn("Some of the given error generators produce instrument deviations outside the span of "
                       "the requested FOMGI sectors; consider sectors='all'.")
    T[_np.abs(T) < 1e-12] = 0.0
    return names, T


def fomgi_quantities(errorgen_rates, sectors='auto', measured_index=0):
    """
    The (first-order) FOMGI quantities of a single-qubit MCM gadget error model.

    Parameters
    ----------
    errorgen_rates : dict
        Gadget error generator rates (two-qubit Pauli strings: measured qubit, virtual qubit).
    sectors : iterable of str, 'all' or 'auto', optional
        See :func:`fomgi_decomposition_matrix`.
    measured_index : int, optional

    Returns
    -------
    OrderedDict
        Maps FOMGI names to values.
    """
    labels = list(errorgen_rates.keys())
    names, T = fomgi_decomposition_matrix(labels, sectors, measured_index)
    eps = _np.array([errorgen_rates[l] for l in labels], dtype=float)
    return _collections.OrderedDict(zip(names, (T @ eps) if len(labels) > 0 else _np.zeros(len(names))))


def all_gadget_errorgen_keys(sectors=('H', 'S'), num_gadget_data_qubits=1):
    """
    All elementary error generator keys of the requested sectors on the gadget space.

    Parameters
    ----------
    sectors : iterable of str, optional
    num_gadget_data_qubits : int, optional

    Returns
    -------
    list of tuple
        ``(type, pauli)`` tuples for 'H'/'S' and ``(type, pauli1, pauli2)`` tuples (``pauli1 < pauli2``
        lexicographically) for 'C'/'A'.
    """
    nq = num_gadget_data_qubits + 1
    paulis = [''.join(p) for p in _itertools.product('IXYZ', repeat=nq)][1:]  # drop identity
    keys = []
    for typ in sectors:
        if typ in ('H', 'S'):
            keys.extend([(typ, p) for p in paulis])
        elif typ in ('C', 'A'):
            keys.extend([(typ, p, q) for p, q in _itertools.combinations(paulis, 2)])
        else:
            raise ValueError("Unknown sector '%s'" % str(typ))
    return keys
