#!/usr/bin/python
import subprocess
import os

def get_branchname():
    try:
        branchname = subprocess.check_output(['bash', '.git/hooks/./.get_branch'])
    except subprocess.CalledProcessError:
        branchname = 'unnamed_branch'
    branchname = os.path.basename(branchname)
    branchname = branchname.replace('\n', '')
    return branchname

updates_git_pages = ['master']
branchname = get_branchname()

if branchname in updates_git_pages:
    subprocess.call(['bash', '.git/hooks/create_git_html'])
        
