#!/usr/bin/python
import subprocess
import os, sys

def get_branchname():
    try:
        branchname = subprocess.check_output(['bash', '.git/hooks/.get_branch'])
    except subprocess.CalledProcessError:
        branchname = 'unnamed_branch'
    branchname = os.path.basename(branchname)
    branchname = branchname.replace('\n', '')
    return branchname

if __name__ == "__main__":

    updates_git_pages = ['master']

    branchname = get_branchname()

    if branchname in updates_git_pages:
        print('Updating github pages!')
        #subprocess.call(['git', 'stash'])
        subprocess.call(['git', 'checkout', 'gh-pages'])
        print(subprocess.check_output(['pwd']))
        os.system('cp temp_html/*.html tutorials/')
        subprocess.call(['git', 'add', 'tutorials/*.html'])
        subprocess.call(['git', 'commit', '-m', '"Updates html in tutorials"'])
        subprocess.call(['git', 'push'])
        subprocess.call(['git', 'checkout', branchname])
        #subprocess.call(['git', 'apply'])

    old_wd = os.getcwd()
    os.chdir('pylint/')
    passes = subprocess.call(['./score.py'])
    os.chdir(old_wd)
    sys.exit(int(passes))
