#!/usr/bin/python
import subprocess
import os

updates_git_pages = ['develop', 'master']

branchname = subprocess.check_output(['sh', 'get_branch'])
branchname = branchname.rsplit('/', 1)[1] # Get the raw branchname

if branchname in updates_git_pages:
    print(os.getcwd())
    # subprocess.call(['git', 'stash'])
    # subprocess.call(['git', 'checkout', ''])
