#!/usr/bin/python
from __future__ import print_function
from utilities  import get_branchname
import subprocess, os, sys

requires_pylint_pass = ['master', 'beta']

if __name__ == '__main__':
    branchname = get_branchname()
    if branchname in requires_pylint_pass:
        old_wd = os.getcwd()
        os.chdir('pylint/')
        passes = subprocess.call(['./score.py'])
        os.chdir(old_wd)
        sys.exit(int(passes))
    else:
        sys.exit(0)

