
# parsetab_string.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = u'ppstringCLOSEBR COLON EXPOP GATE INSTRMT INTEGER LPAREN MULTOP NOP OPENBR POVM PREP REFLBL RPAREN STRINGINDstrref  : STRINGIND REFLBLslcref : strref OPENBR INTEGER COLON INTEGER CLOSEBRslcref : strrefexpable : LPAREN string RPARENexpable : GATE\n                   | INSTRMT\n                   | NOP expable : slcrefexpdstr : expable EXPOP INTEGERexpdstr : expablestring : expdstrstring : string expdstrstring : string MULTOP expdstrpstring : stringpstring : PREP stringppstring : pstringppstring : pstring POVM'
    
_lr_action_items = {u'RPAREN':([1,3,4,5,6,9,12,15,19,20,22,23,25,28,],[-10,-5,-8,-3,-6,-11,-7,-12,25,-1,-9,-13,-4,-2,]),u'EXPOP':([1,3,4,5,6,12,20,25,28,],[14,-5,-8,-3,-6,-7,-1,-4,-2,]),u'STRINGIND':([0,1,2,3,4,5,6,8,9,12,13,15,16,19,20,21,22,23,25,28,],[10,-10,10,-5,-8,-3,-6,10,-11,-7,10,-12,10,10,-1,10,-9,-13,-4,-2,]),u'POVM':([1,2,3,4,5,6,7,9,12,15,20,21,22,23,25,28,],[-10,-14,-5,-8,-3,-6,18,-11,-7,-12,-1,-15,-9,-13,-4,-2,]),u'INTEGER':([14,17,26,],[22,24,27,]),u'OPENBR':([5,20,],[17,-1,]),u'CLOSEBR':([27,],[28,]),u'INSTRMT':([0,1,2,3,4,5,6,8,9,12,13,15,16,19,20,21,22,23,25,28,],[6,-10,6,-5,-8,-3,-6,6,-11,-7,6,-12,6,6,-1,6,-9,-13,-4,-2,]),u'COLON':([24,],[26,]),u'MULTOP':([1,2,3,4,5,6,9,12,15,19,20,21,22,23,25,28,],[-10,16,-5,-8,-3,-6,-11,-7,-12,16,-1,16,-9,-13,-4,-2,]),u'LPAREN':([0,1,2,3,4,5,6,8,9,12,13,15,16,19,20,21,22,23,25,28,],[8,-10,8,-5,-8,-3,-6,8,-11,-7,8,-12,8,8,-1,8,-9,-13,-4,-2,]),u'REFLBL':([10,],[20,]),u'GATE':([0,1,2,3,4,5,6,8,9,12,13,15,16,19,20,21,22,23,25,28,],[3,-10,3,-5,-8,-3,-6,3,-11,-7,3,-12,3,3,-1,3,-9,-13,-4,-2,]),u'NOP':([0,1,2,3,4,5,6,8,9,12,13,15,16,19,20,21,22,23,25,28,],[12,-10,12,-5,-8,-3,-6,12,-11,-7,12,-12,12,12,-1,12,-9,-13,-4,-2,]),u'PREP':([0,],[13,]),'$end':([1,2,3,4,5,6,7,9,11,12,15,18,20,21,22,23,25,28,],[-10,-14,-5,-8,-3,-6,-16,-11,0,-7,-12,-17,-1,-15,-9,-13,-4,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {u'expdstr':([0,2,8,13,16,19,21,],[9,15,9,9,23,15,15,]),u'string':([0,8,13,],[2,19,21,]),u'strref':([0,2,8,13,16,19,21,],[5,5,5,5,5,5,5,]),u'ppstring':([0,],[11,]),u'expable':([0,2,8,13,16,19,21,],[1,1,1,1,1,1,1,]),u'pstring':([0,],[7,]),u'slcref':([0,2,8,13,16,19,21,],[4,4,4,4,4,4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ppstring","S'",1,None,None,None),
  (u'strref -> STRINGIND REFLBL',u'strref',2,'p_strref','gatestringparser.py',146),
  (u'slcref -> strref OPENBR INTEGER COLON INTEGER CLOSEBR',u'slcref',6,'p_slcref_slice','gatestringparser.py',153),
  (u'slcref -> strref',u'slcref',1,'p_slcref','gatestringparser.py',159),
  (u'expable -> LPAREN string RPAREN',u'expable',3,'p_expable_paren','gatestringparser.py',164),
  (u'expable -> GATE',u'expable',1,'p_expable_single','gatestringparser.py',169),
  (u'expable -> INSTRMT',u'expable',1,'p_expable_single','gatestringparser.py',170),
  (u'expable -> NOP',u'expable',1,'p_expable_single','gatestringparser.py',171),
  (u'expable -> slcref',u'expable',1,'p_expable','gatestringparser.py',176),
  (u'expdstr -> expable EXPOP INTEGER',u'expdstr',3,'p_expdstr_expop','gatestringparser.py',181),
  (u'expdstr -> expable',u'expdstr',1,'p_expdstr','gatestringparser.py',186),
  (u'string -> expdstr',u'string',1,'p_string_expdstr','gatestringparser.py',191),
  (u'string -> string expdstr',u'string',2,'p_string_str','gatestringparser.py',196),
  (u'string -> string MULTOP expdstr',u'string',3,'p_string','gatestringparser.py',201),
  (u'pstring -> string',u'pstring',1,'p_pstring','gatestringparser.py',206),
  (u'pstring -> PREP string',u'pstring',2,'p_pstring_prep','gatestringparser.py',211),
  (u'ppstring -> pstring',u'ppstring',1,'p_ppstring','gatestringparser.py',216),
  (u'ppstring -> pstring POVM',u'ppstring',2,'p_ppstring_povm','gatestringparser.py',221),
]
